### ISSUE TITLE
verify output of test_IN codes

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/NCEPLIBS-bufr#104]
Following last week's NCEPLIBS discussion, I went and did a deeper dive to confirm how the testing is currently working for the 5 test_IN codes (i.e. the non-utility codes which test the decoding/reading of canned BUFR files using different subprograms from the library).  As it turns out, the automated testing that was set up a while back is running these codes, but it's not actually verifying the output by confirming that none of the underlying checks failed.  I confirmed this by manually changing one of these codes in a clone of the repository and re-running the test.  With the changes I made, the check for this particular code should have failed, but ctest went ahead and passed it anyway.  So bottom line, these tests still aren't fully implemented, because ctest is only running the codes and not actually verifying the output.

This issue only affects the 5 existing test_IN codes.  The 5 corresponding test_OUT codes (i.e. the non-utility codes which test the encoding/writing of BUFR files) are fully implemented and do have their output properly verified.

**Comment by edwardhartnett** [comment]
Excellent catch! I will frequently write the test to fail at first, just to test that failure is caught appropriately...
