### ISSUE TITLE
ufbrep, unideal behavior

### ISSUE THREAD

**Issue by rmclaren** [NOAA-EMC/NCEPLIBS-bufr#130]
I think the following is intended behavior, but I just wanted to make note of it (please don't feel like you have to write an extensive reply to this issue).

So when reading radiance data (like MHS) the mnemonics CHMN and TMBR occur within the same fixed repeated sequence. The issue is that ufbrep will generate different results depending on the ordering of CHMN and TMBR (the ordering in the BUFR file is CHMN then TMBR).

So if you call:
  _**ufbrep(fileunit, data, nx, ny, iret, "CHMN TMBR")**_ you get the correct values
if you call it like this:
  _**ufbrep(fileunit, data, nx, ny, iret, "TMBR CHMN")**_ the values returned for CHMN will be incorrect (they will reflect the values for the NEXT repeat, not the current one)

**Comment by jbathegit** [comment]
Yes, that is the intended behavior.  The first mnemonic in ufbrep is always treated like a pivot, so in your second case, the pivot is TMBR, meaning that the first CHMN it will return is the one between the first and second occurrences of TMBR, which in this case would then be the second occurrence of CHMN.

A more detailed discussion of this, including the concept of pivot mnemonics and the subtle differences between ufbint, ufbrep, ufbseq and ufbstp, is available from https://emc.ncep.noaa.gov/emc/pages/infrastructure/bufrlib_jeff/html/md__gpfs_dell2_emc_obsproc_noscrub_Jeff_8Ator_NCEPLIBS-bufr-GitHub_nceplibs-bufr_docs_dfbftab.html#ufbsubs, as part of the Doxygen updates that I've been working on.
