### ISSUE TITLE
Turn 11.4.0 into full release...

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#131]
It was released as a draft, but it has been used a little, so let's just go ahead and make it a release. That means:

* Release notes
* Do a github release (not just a tag, though this includes a tag)
* Documentation release to gh-pages branch to go with version
* Tarball contains everything needed to build and test (check for cmake files)

@jbathegit I would suggest that you assign this issue to yourself. The Code Manager is the best one to be making releases...

**Comment by jbathegit** [comment]
Will do, though I may need a little hand-holding along the way since this will be my first release from GitHub.  Just want to make sure I don't miss anything important ;-)

**Comment by edwardhartnett** [comment]
I think all you have to do is publish the release and update the docs...

**Comment by edwardhartnett** [comment]
OK, we did this.
