### ISSUE TITLE
binv utility does not work as documented

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/NCEPLIBS-bufr#141]
As currently documented, the binv utility is to be run as `binv.x filename`, where `filename` is the name of the file to be inventoried.  However, this doesn't work as advertised, and in this case the executable just hangs in a perpetual waiting state.  This behavior was noted on both hera and on WCOSS/Dell.  Looking at the binv source code, it's doing a `read(5,'(a)') file` to get the filename, and apparently this doesn't work when the filename is a command-line argument.

However, it does work if you just type in the name of the executable `binv.x` and hit \<Enter\>, and then, when it's sitting there waiting for input, paste in the `filename` and hit \<Enter\> again.  If this is the way the utility is really designed to work(?), then we need to update the documentation accordingly in the Sample Utilities section of the documentation, and in this case it might also be helpful for the user to have the executable spit out a prompt such as `Enter [path/]name of file to be inventoried:` to let them know it's waiting for a filename.  Otherwise, and if the intent is really for the `filename` to be passed as a command-line argument, then the code needs to be tweaked a bit.

This is related to #91, given that we currently don't have a test case for this or many of the other Sample Utilities.  @jack-woollen, could you please take a look at this when you have some time?

**Comment by ShelleyMelchior-NOAA** [comment]
Thanks for this tip. The work-around as @jbathegit advised works for me for binv and sinv. One other note, however, the prod_envir variables $DCOMROOT and $COMROOT are not recognized when you provide a valid path and bufr file. You must expand those environment variables.

**Doesn't work:**
```
$ ./sinv.x 
$DCOMROOT/20220216/b003/xx010
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 20, file /lfs/h2/emc/ptmp/Shelley.Melchior/build/utils/$DCOMROOT/20220216/b003/xx010
Image              PC                Routine            Line        Source             
sinv.x             000000000043F6CB  Unknown               Unknown  Unknown
sinv.x             00000000004566A0  Unknown               Unknown  Unknown
sinv.x             00000000004042F2  MAIN__                     30  sinv.f
sinv.x             00000000004041D2  Unknown               Unknown  Unknown
libc-2.26.so       00001539D81293EA  __libc_start_main     Unknown  Unknown
sinv.x             00000000004040EA  Unknown               Unknown  Unknown
```

**Works:**
```
$ ./sinv.x
 /lfs/h1/ops/prod/dcom/20220216/b003/xx010
 
003           417  
005           399  
042            26  
043            12  
044            90  
269          2815  
750           717  
751           804  
752           764  
753           738  
754           828  
755           767  
803            82  
804           117  
825            22
```
