### ISSUE TITLE
A seemingly abnormal behavior in ipks.f of bufr lib called from writsb in  GSI oneobmod.f90

### ISSUE THREAD

**Issue by TingLei-NOAA** [NOAA-EMC/NCEPLIBS-bufr#146]
When running current GSI using the latest bufr lib (11.5.0 ) cloned from github, a seemingly abnormal behaivor in ipks.f was found which would cause "floating invalid " abortion of GSI when the later was built with debug mode. When running GSI with non-debug mode, the same behavior (same values for printed out var) was found though the GSI would run pass that point.
The problem is in FUNCTION IPKS(VAL,NODE) , ipks.f (with printing-out lines added for debugging purpose).
^^
`
write(6,)"thinkdebbufr val is ",VAL
call flush(6)
write(6,)"thinkdebbufr NODE is ",NODE
call flush(6)
write(6,)"thinkdebbufr ISC is ",ISC(NODE)
call flush(6)
write(6,)"thinkdebbufr IRF is ",IRF(NODE)
call flush(6)

write(6,*)'thinkdebbufr 2 is', VAL * TEN**(ISC(NODE))                
  call flush(6)
write(6,*)'thinkdebbufr 3 is ',NINT( VAL * TEN**(ISC(NODE)) )
  call flush(6)
IPKS = NINT( VAL * TEN**(ISC(NODE)) ) - IRF(NODE)`
V
The problem occurred when
^^
0: thinkdebbufr val is 1000000000.00000
0: thinkdebbufr NODE is 57
0: thinkdebbufr ISC is 1
0: thinkdebbufr IRF is -2732
0: thinkdebbufr 2 is 10000000000.0000
V
Then, the GSI with debug mode would abort , while the GSI without debug mode used would give
^^
0: thinkdebbufr val is 1000000000.00000
0: thinkdebbufr NODE is 57
0: thinkdebbufr ISC is 1
0: thinkdebbufr IRF is -2732
0: thinkdebbufr 2 is 10000000000.0000
0: thinkdebbufr 3 is -2147483648
.........
VV
And the program would run passing this point.
The problem occurred in GSI in the subroutine oneobmakebufr of https://github.com/NOAA-EMC/GSI/blob/master/src/gsi/oneobmod.F90 (line 332)
'call writsb(lendian_in)'
It is very likely a problem with how I ran GSI not the issue with the bufr lib. However, I am clueless now on what is the possible reason. Your comments/suggestions are appreciated.

**Comment by jbathegit** [comment]
Hello, and sorry you're experiencing a problem.  I'm also bringing @jack-woollen into this discussion in case he may be able to help.

For my part, I'm having trouble understanding the problem without some more information.  For one thing, it looks like IPKS is being called with a value of 1000000000.0 (=10E10), which is the default "missing" value in the library.  However, the only place that IPKS is called from within the library is inside of WRTREE, where it's protected within the following code block:

         IF(IBFMS(VAL(N,LUN)).EQ.0) THEN
            IVAL(N) = IPKS(VAL(N,LUN),NODE)
         ELSE
            IVAL(N) = -1
         ENDIF

and where IBFMS is a function that checks for the "missing" value.  In other words, and assuming that you're using 10E10 as your "missing" value, I'm having trouble understanding how IPKS was ever even called with that value in the first place; rather, it should have just dropped to the ELSE block and set IVAL(N) = -1.  Can you confirm that the value bmiss in your oneobmod.F90 code is 10E10?  Could you also point me to a copy of the BUFR table you're using as input, and print out the character string TAG(NODE) so I can see what mnemonic it's trying to write a value for?

Better yet, could you perhaps provide a small test code (i.e. smaller than the entire GSI code) and input data case which shows this behavior, and let me know what compiler and build of the library you're using?  All in all, it would really help me to be able to reproduce this behavior myself, so I can better try to debug it to figure out what's going on here.

**Comment by TingLei-NOAA** [comment]
Jeff,
Thank you so much!
Yes, seems you already identified where the problem came from.  Those
values (1E9) are from the missing values set up in the GSI.  I changed it
to 1E10 in case 1E9 is not recognized by bufr lib ,  it is still the case:
that missing value also caused the problem.
The bufr table i am using is
/scratch2/NCEPDEV/fv3-cam/Ting.Lei/dr-regional-workflow/regional_workflow//sorc/regional_gsi.fd/fix/prepobs_prep.bufrtable.
Really appreciate your willingness to help with a test case, I will try to
make one if it is needed. Though, I feel , thankfully, you already narrowed
down to the probable reason.
Your further comments/clarifications are appreciated.
Ting






______________________________

Ting Lei

IMSG at NOAA/NWS/NCEP/EMC

5830 University Research Ct., Cubicle 2765

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3624

**Comment by TingLei-NOAA** [comment]
Hi, Jeff,
An update, tracing the IBFMS function you pointed to, seems in my run, in
bufr , the missing value used in ibfms  is 1E11, while, in GSI, there are
compiler options as
^
#ifdef ibm_sp
  real(r_kind), parameter:: emiss = 1.0e11_r_kind
#else
  real(r_kind), parameter:: bmiss = 1.0e9_r_kind
#endif
V
  It is the bmiss=1E9 that was used which caused the problem.
I would see (maybe consult with Mike) to see how the missing values setup
in this part of GSI and bufr could be consistent.
Your help is really appreciated.
Regards,
Ting

______________________________

Ting Lei

IMSG at NOAA/NWS/NCEP/EMC

5830 University Research Ct., Cubicle 2765

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3624

**Comment by jbathegit** [comment]
Hi Ting,
The proper way to do this sort of thing is to have the application code call subroutine [setbmiss](https://noaa-emc.github.io/NCEPLIBS-bufr/setbmiss_8f.html) to set a custom "missing" value within the NCEPLIBS-bufr library.  The code can also call subroutine [getbmiss](https://noaa-emc.github.io/NCEPLIBS-bufr/getbmiss_8f.html) at any time to check what the current "missing" value is set to.

**Comment by TingLei-NOAA** [comment]
Jeff,
Thanks a lot.  I agree.  That is the good way to do that.  I will follow
your suggestion on this.
This issue can be closed.
Again, really appreciate your prompt help!
Ting

______________________________

Ting Lei

IMSG at NOAA/NWS/NCEP/EMC

5830 University Research Ct., Cubicle 2765

College Park, MD 20740

***@***.*** ***@***.***>

301-683-3624
