### ISSUE TITLE
Start adding links to GitHub issues in releases, also refer to GitHub project

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#148]
In our future releases, we should add links to closed issues in our list of new features. Also, we should include a link to the appropriate github project. See https://github.com/NOAA-EMC/UFS_UTILS/releases/tag/ufs_utils_1_5_0 for a good example.

Basically, we want users to be able to click through to find out every issue associated with a release. They don't all have to be listed in the release, but the important ones should be. The rest can be found through the project, which should contain every issue closed for that release.

The best way to do this is to draft the release notes for the next release, as soon as a release is done. That gives a place where important changes can be listed as they are completed, so that doing a release, we can already have the list of changes, and don't have to go track down exactly what was done. For example, when @GeorgeGayno-NOAA did the UFS_UTILS 1.5.0 release, he immediately added draft release notes for the 1.6.0 release. (When editing the draft release notes, take care to save changes with "Save to Draft" instead of "Do Release".) See https://github.com/NOAA-EMC/UFS_UTILS/releases to see how this looks in practice.

@jbathegit if you concur, please assign this issue to yourself.

**Comment by jbathegit** [comment]
All done in new bufr_v11.6.0 release, and next draft release has now been established as bufr_v11.7.0
