### ISSUE TITLE
python api does not build

### ISSUE THREAD

**Issue by nuitlejour** [NOAA-EMC/NCEPLIBS-bufr#149]
when I turn on the 'option(ENABLE_PYTHON "Enable building python module 'ncepbufr'" ON)' in CMakeLists.txt, python api tests all failed, rest of the tests are OK.

**Comment by edwardhartnett** [comment]
Did you get this to work? What was the problem?

We want this to work out of the box, so if it doesn't, let us know why and we can fix...

**Comment by nuitlejour** [comment]
I think the problem arise from my conda python environment. the python in conda is compiled by gcc 9.3, and I am using fedora 34, which is gcc 11.1. 
the work around I found is: install gcc/gfortran in my conda environment and specify -DCMAKE_Fortran_COMPILER, -DCMAKE_C_COMPILER to my conda gcc/gfortran.
