### ISSUE TITLE
increase maximum [path/]filename length for input to COBFL

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/NCEPLIBS-bufr#174]
A WCOSS2 user has asked if we could increase the maximum allowable [path/]filename length of a BUFR file that can be passed in to subprogram COBFL.  The limit is currently set to 100 characters, and the user has requested an increase to 150 characters.

**Comment by kgerheiser** [comment]
Instead of coding hardcoding 100 or 150, can you use the Posix constant `PATH_MAX` in `#include <limits.h>`?

**Comment by jbathegit** [comment]
> Instead of coding hardcoding 100 or 150, can you use the Posix constant `PATH_MAX` in `#include <limits.h>`?

I suppose I could, but that's equivalent to 4096 on the WCOSS, which I think is way too big, especially in case I need to echo this value back out in an error string.

I also checked `FILENAME_MAX` in <stdio.h>, but that's also set to 4096.

**Comment by aerorahul** [comment]
use `trim()` to remove blank space from the string.

**Comment by jbathegit** [comment]
> use `trim()` to remove blank space from the string.

Thanks, but this is C code, not F90.  And I can't just use something like strlen(), because the subprogram is callable from Fortran, which means there may not always be a trailing NULL.  So what the code does now is loop through the input string and use !isspace() and !iscntrl() to know where to set the trailing NULL.

**Comment by jbathegit** [comment]
I decided to just bump it to 200.   That should be plenty large for all practical purposes, and if people still need longer names within their application codes, they can always change filenames or working directories within their scripts, or just use symbolic links.

In other words, there are always options at the OS level to shorten the length of the [path/]filename that actually gets passed in to this subprogram.  I really think that bumping all the way up to `PATH_MAX` or `FILENAME_MAX` is overkill.
