### ISSUE TITLE
new release 11.6.0

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/NCEPLIBS-bufr#180]
What needs to be done:

* increment number in VERSION file
* generate docs and update gh-pages branch with the new html
* update release notes, in both GitHub and in ReleaseNotes.md
* do a pull request from develop to master branch, linking this issue
* create a new hpc-stack issue to incorporate this new version

**Comment by edwardhartnett** [comment]
What we have been doing elsewhere is just deleting the master branch altogether. It's not needed.

**Comment by jbathegit** [comment]
master branch is now deleted, re: #181

**Comment by jbathegit** [comment]
All of the above steps have been completed.  The release has now been published, and an hpc-stack ticket has been opened (see https://github.com/NOAA-EMC/hpc-stack/issues/362)
