### ISSUE TITLE
delete master branch

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#181]
We are deleting the master branch of all NCEPLIBS repos.

develop will remain the development branch as it has been.

@jbathegit perhaps you would like to do this...

**Comment by jbathegit** [comment]
I'm willing to do this, but it says the master branch is protected and can't be deleted(?)

**Comment by kgerheiser** [comment]
You can change branch protection rules in repo settings.

**Comment by jbathegit** [comment]
Yeah, I did a lookup in Settings->Branches->Branch Protection Rules->Master, and it looks like I can just delete the rule.  I'll give it a try...

**Comment by jbathegit** [comment]
OK, it's done!
