### ISSUE TITLE
Line truncated error in bfrini.f90 when using long paths

### ISSUE THREAD

**Issue by kgerheiser** [NOAA-EMC/NCEPLIBS-bufr#182]
I'm building bufr inside of Spack which contains long paths and building with GCC fails with:

```
  Error: Line truncated at (1) [-Werror=line-truncation]
```

That is because of the include of `@MASTER_TABLE_DIR@` in `bfrini.f90`:

https://github.com/NOAA-EMC/NCEPLIBS-bufr/blob/3f2e10bdfa3c6ef179e9e0e9ffb03287b3eba31a/src/bfrini.f90.in#L285

The Fortran standard limits line lengths to 132, but it's possible for a filesystem path to be longer than this.

It's possible to override this error with `-ffree-line-length-none`, but maybe there's a better solution. Is there another way of using `@MASTER_TABLE_DIR@` without it being a hardcoded path in the source code?

If possible installs should be relocatable, and hardcoding the install path into the source code doesn't seem safe.

**Comment by jbathegit** [comment]
Hi @kgerheiser, this relates back to issue #123 from last year where there was a lot of discussion about ways to do this, including my reply on March 23rd where the line length detail was specifically mentioned.

Bottom line, I implemented the best solution I could come up with and which (I thought? ;-) everyone was happy with at the time, but I'm amenable to changing it again now if you have an idea for a better way to do this - just let me know what you suggest.

**Comment by kgerheiser** [comment]
Just spitballing here, but the only other way I see to handle the master tables are to somehow embed them directly in the program as a Fortran array. The build system could convert the tables, or it could be tracked directly in Git and manually updated whenever there's a change to the table.

But that's an involved process. I think just passing `-ffree-line-length-none` is the immediate solution to this problem. Ifort allows longer lines by default.
