### ISSUE TITLE
convert to using Fortran/C API 

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#20]
There is now a standard way to call C from Fortran.

We are doing this sort of thing, but it is no longer necessary (from src/bufrlib.h):

```
/*
** On certain operating systems, the FORTRAN compiler appends an underscore
** to subprogram names in its object namespace.  Therefore, on such systems,
** a matching underscore must be appended to any C language references to
** the same subprogram names so that the linker can correctly resolve such
** references across the C <-> FORTRAN interface at link time.  This needs
** to be done for any subprogram that is either:
**   1) a C function, or
**   2) a FORTRAN subprogram called from C
*/
#ifdef UNDERSCORE
#define arallocc   arallocc_
#define ardllocc   ardllocc_
...
```

**Comment by jbathegit** [comment]
I haven't forgotten about this, but I'd like to get the (official ;-) 11.4.0 release out, so I'll work on this one as part of the next subsequent release.

It shouldn't be too difficult to replace all of the #ifdef UNDERSCORE defines with BIND(C) attributes on the corresponding functions, or something similar.

**Comment by jbathegit** [comment]
Sorry, accidentally hit "Close" on this, so just re-opened ;-)

**Comment by jbathegit** [comment]
I'm going to close this issue and leave #79 open, since they both cover the same topic.
