### ISSUE TITLE
bufr_interface.f90 won't build on orion

### ISSUE THREAD

**Issue by jack-woollen** [NOAA-EMC/NCEPLIBS-bufr#201]
/work/noaa/da/jwoollen/jwfork/NCEPLIBS-bufr/src/bufr_interface.f90:413.11:

  allocate(jmpb_f, source=jmpb)
           1
Error: Array specification required in ALLOCATE statement at (1)
/work/noaa/da/jwoollen/jwfork/NCEPLIBS-bufr/src/bufr_interface.f90:393.11:

  allocate(tag_f, source=tag)
           1
Error: Array specification required in ALLOCATE statement at (1)
/work/noaa/da/jwoollen/jwfork/NCEPLIBS-bufr/src/bufr_interface.f90:371.11:

  allocate(typ_f, source=typ)
           1
Error: Array specification required in ALLOCATE statement at (1)
/work/noaa/da/jwoollen/jwfork/NCEPLIBS-bufr/src/bufr_interface.f90:350.11:

  allocate(itp_f, source=itp)
           1
Error: Array specification required in ALLOCATE statement at (1)
/work/noaa/da/jwoollen/jwfork/NCEPLIBS-bufr/src/bufr_interface.f90:331.11:

  allocate(link_f, source=link)
           1
Error: Array specification required in ALLOCATE statement at (1)
/work/noaa/da/jwoollen/jwfork/NCEPLIBS-bufr/src/bufr_interface.f90:312.11:

  allocate(isc_f, source=isc)
           1
Error: Array specification required in ALLOCATE statement at (1)
make[2]: *** [src/CMakeFiles/bufr_d_f.dir/bufr_interface.f90.o] Error 1

**Comment by rmclaren** [comment]
Which compiler is being used. 

Its most likely they are using a really old version of Fortran. Do we need to modify the code to accommodate that? What is the minimum version of Fortran that NCEPLIB-BUFR supports?

**Comment by rmclaren** [comment]
So I just pushed a new branch that should work better with old versions of fortran (**feature/orion_fix**). Could someone try it out on Orion under the offending account and confirm that it solves the problem. If it does I'll issue a PR.

**Comment by rmclaren** [comment]
Forgot to check in the changes, so just did that. Should be good now (if you jumped in in the last 7 min).

**Comment by jack-woollen** [comment]
@rmclaren  The compiler cmake uses is GNU/4.8.5. Orion has newer compilers. How does cmake pick the one it uses?

Anyway, the bufrlib did compile on your new branch. But the test didn't.

/work/noaa/da/jwoollen/jwfork/NCEPLIBS-bufr/test/test_c_interface.c: In function ‘test_intrusiveInterface’:
/work/noaa/da/jwoollen/jwfork/NCEPLIBS-bufr/test/test_c_interface.c:165:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int i = 0; i < NumSubsetsToParse; i++)
     ^
/work/noaa/da/jwoollen/jwfork/NCEPLIBS-bufr/test/test_c_interface.c:165:5: note: use option -std=c99 or -std=gnu99 to compile your code
/work/noaa/da/jwoollen/jwfork/NCEPLIBS-bufr/test/test_c_interface.c:240:17: error: ‘for’ loop initial declarations are only allowed in C99 mode
                 for (int dataCursor = 1; dataCursor <= nval; dataCursor++)
                 ^
/work/noaa/da/jwoollen/jwfork/NCEPLIBS-bufr/test/test_c_interface.c:314:14: error: redefinition of ‘i’
     for (int i = 0; i < NumSubsetsToParse; i++)
              ^
/work/noaa/da/jwoollen/jwfork/NCEPLIBS-bufr/test/test_c_interface.c:165:14: note: previous definition of ‘i’ was here
     for (int i = 0; i < NumSubsetsToParse; i++)
              ^
/work/noaa/da/jwoollen/jwfork/NCEPLIBS-bufr/test/test_c_interface.c:314:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int i = 0; i < NumSubsetsToParse; i++)
     ^
make[2]: *** [test/CMakeFiles/test_c_interface_4.x.dir/test_c_interface.c.o] Error 1
make[1]: *** [test/CMakeFiles/test_c_interface_4.x.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Built target test_OUT_4_4.x
[ 98%] Built target test_OUT_2_4.x
[ 98%] Built target test_OUT_5_4.x
make: *** [all] Error 2

**Comment by rmclaren** [comment]
Ok, I updated the syntax in the test file so hopefully it will compile now without needing the c99 compiler flag (if you want to do a git pull and try it again)... 

Generally cmake will use the compiler that's configured for you're shell environment. So it depends on how the account is configured...

**Comment by kgerheiser** [comment]
@jack-woollen 

CMake picks the compiler using the standard environment variables `CC`, `FC`, `CXX`, or with the CMake variables `CMAKE_C_COMPILER`, `CMAKE_Fortran_COMPILER`, `CMAKE_CXX_COMPILER`. Generally, it's easiest to use the env variables. Or it picks a default one if you don't have that set, usually the system GCC.

**Comment by jack-woollen** [comment]
@rmclaren @kgerheiser  So, with the default gnu compiler it now compiles the test, but then fails running one of the tests, not sure which one. Moving up to Intel 19.1.2.20200623, it then passes all the tests and completes properly. Just to check, I went back to the original develop branch and tried the intel compiler on that, but no dice, bufr_interface still doesn't compile. So, thanks for making the updates.
