### ISSUE TITLE
LIB=/path/to/bufrlib.a

### ISSUE THREAD

**Issue by wangyutao143** [NOAA-EMC/NCEPLIBS-bufr#205]
How should LIB be modified in the ./install/install.sh script
LIB=/path/to/bufrlib.a

**Comment by jbathegit** [comment]
Hello!  Where in your build are you seeing a ./install/install.sh script?  AFAIK there shouldn't be any such file in the distribution package, nor should one be generated during the automated build process.

Instead, the library should be installed automatically during the `make install` step, into whatever path you defined via the `-DCMAKE_INSTALL_PREFIX` flag during the previous `cmake` step.

**Comment by wangyutao143** [comment]
Dear Jeff Ator,

Thank you for your help，I have analyzed the file of ground and upper level (please see the attachments for the analyzed results), and now I have some further questions according these results.

1.&nbsp; &nbsp; What do those abbreviations mean in rec type (sfcshp, adpsfc, etc.) as well as obs type (LCMAN, TIDEG, etc.)? It would be best if you could provide me with a table about the explanation of those abbreviations as a reference.

2.&nbsp; &nbsp; For Station BBSSS, does it mean the name of the station?

3.&nbsp; &nbsp; What do ELEV, STN PR, STN DSLP, ALTIM mean?

4.&nbsp; &nbsp; I did NOT find the elements related to the ocean and cloud such as significant wave height, direction of wave, cloud cover, height about surface of base of lowest cloud see, etc., whereas there should be some related to ocean based on the information given by some studies.

5.&nbsp; &nbsp; In the file of “gdas.adpupa.t00z.20200101”, STAN ELEV: 1, 2, 3, …, 130. I suppose that there numbers are the height of the observation, but I have no idea about the unit of this column of data.

Hope to hear from you soon, and sincerely appreciate your kind help with my questions.

&nbsp;

Best regards,

Tao Wang


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "NOAA-EMC/NCEPLIBS-bufr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 凌晨0:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NOAA-EMC/NCEPLIBS-bufr] LIB=/path/to/bufrlib.a (Issue #205)





 
Hello!  Where in your build are you seeing a ./install/install.sh script?  AFAIK there shouldn't be any such file in the distribution package, nor should one be generated during the automated build process.
 
Instead, the library should be installed automatically during the make install step, into whatever path you defined via the -DCMAKE_INSTALL_PREFIX flag during the previous cmake step.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

Analyzied Files.rar (13.05M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=2c32396414534a9c0290d0351165574c5456005352065c0549015a5c074851055c01145d0157004e56530154015c500053060806377665220a53551d4d0c00074474500852164b1105403959&t=exs_ftn_download&code=d29d7eec

**Comment by jbathegit** [comment]
First of all, I didn't see any attachments (unless I missed something).

But more significantly, your questions have more to do with the contents of one or more specific NCEP BUFR files, rather than concerns about the NCEPLIBS-bufr library itself.  This forum is for questions/concerns about the library, not for questions about specific NCEP BUFR files.  So you may instead want to contact some of my colleagues via the email support address obsproc_support@noaa.gov, and please be sure to include any relevant attachments when you do so.

**Comment by wangyutao143** [comment]
I don't know how to use&nbsp;ds351.0 and ds461.0 data
I provided the attachment again

------------------ 原始邮件 ------------------
发件人:                                                                                                                        "NOAA-EMC/NCEPLIBS-bufr"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月13日(星期五) 凌晨5:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NOAA-EMC/NCEPLIBS-bufr] LIB=/path/to/bufrlib.a (Issue #205)





 
First of all, I didn't see any attachments (unless I missed something).
 
But more significantly, your questions have more to do with the contents of one or more specific NCEP BUFR files, rather than concerns about the NCEPLIBS-bufr library itself.  This forum is for questions/concerns about the library, not for questions about specific NCEP BUFR files.  So you may instead want to contact some of my colleagues via the email support address ***@***.***, and please be sure to include any relevant attachments when you do so.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

gdas.aircft.t00z.20090430.txt (1.83M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=64636663eb94dbca50c18f3214370b1a0607025b51010e051b560253061a0d5152054b5a03060b1801555e07515309060f015356322a39525202154d535e4b56501748170207431b0453565a02030a0518171e17320a&code=6cfc2795




gdas.adpupa.t00z.20200101.txt (11.81M, 无限期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=616132342d9971c755c3db651263011750040a000d06525e1e57530c074e070f01571f560d0007155258515501060b0050520201347e335f5700411a5507434d43001c400453491601510004045203091d154a40345e&code=3a244c38
