### ISSUE TITLE
Need to tag a new release version of NCEPLIB-bufr (maybe bufr_v11.7.0)

### ISSUE THREAD

**Issue by rmclaren** [NOAA-EMC/NCEPLIBS-bufr#206]
In order to make it practical to release the BUFR querying functions for ioda-converters we will need a new numbered tag for NCEPLIB-bufr. This feature depends on the latest additions to the NCEPLIB-bufr c interface which are not present in the most recent tag that is available. The tag number is used to manage the dependencies that ioda-converters is dependent on in the production environment.

**Comment by jbathegit** [comment]
What needs to be done:

- increment number in VERSION file
- update release notes, in both GitHub and in ReleaseNotes.md
- generate docs and update gh-pages branch with the new html
- create a new hpc-stack issue to incorporate this new version

**Comment by jbathegit** [comment]
I just released the new v11.7.0.  I'll open up an hpc-stack issue to have it built on all relevant NCEP systems.
