### ISSUE TITLE
VERSION file wrong, also future versions should use standard version number, like other NCEPLIBS projects...

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#21]
The current version in the VERSION file is:
11.3.1.1

But there is a tagged release 11.4.0.

OK, we don't need 4 numbers. 3 works for every other project and will work well for this one too. ;-) So the VERSION file should be updated to 11.4.0.

The next release can be 11.5.0 or 11.4.1...

**Comment by aerorahul** [comment]
major.minor.patch.tweak is semantic versioning. 
Though, we don't tweak much.

**Comment by edwardhartnett** [comment]
Let's use a 3-part number on this project as we do all the other NCEPLIBS. That will be enough to get by, I'm sure.

**Comment by edwardhartnett** [comment]
This was fixed with #30
