### ISSUE TITLE
Python wrapper for readlc function

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/NCEPLIBS-bufr#226]
Per an email request from jack.reeveseyre@noaa.gov, who works in NCEP/CPC:

When decoding ASCII data (e.g., station names) there is a mismatch between different python function results:
read_subset() cuts off the output at 8 characters;
print_subset() and dump_subset() produce the full name.
Do you know of a way to get the full result from the read_subset() call?

**Comment by jbathegit** [comment]
The mismatch, as you put it, is due to the different underlying Fortran routines that read_subset calls, as opposed to those called by print_subset and dump_subset.  More specifically, read_subset uses the underlying routines [ufbint](https://noaa-emc.github.io/NCEPLIBS-bufr/ufbint_8f.html), [ufbseq](https://noaa-emc.github.io/NCEPLIBS-bufr/ufbseq_8f.html), [ufbrep](https://noaa-emc.github.io/NCEPLIBS-bufr/ufbrep_8f.html), etc., each of which only deal with decoded data in 8-byte chunks, and which is why they can't be used to return character values which are longer than 8-bytes, such as long station names.

As explained in the referenced documentation (see the above links), what needs to be done to return such values is to instead use the underlying Fortran routine [readlc](https://noaa-emc.github.io/NCEPLIBS-bufr/readlc_8f.html), which can handle longer character strings of arbitrary length, and which is called indirectly by print_subset and dump_subset through yet another layer of underlying Fortran routines.  So that's why you see the longer character strings fully printed in your output from print_subset and dump_subset.

I don't know of any easy way to get around this at the moment.  What would probably be the best longer-term solution would be to develop a Python-based wrapper for readlc (maybe call it read_long_string or something like that), then add that to the Python interface as part of a future version release of the library.

**Comment by JackReevesEyre** [comment]
I had a go at writing a python wrapper that solves this. It is very simple and seems to solve the problem in my use case. But I've done only limited testing and exception handling. Anyway, I can provide it for the repository if that would be helpful. Please let me know how to proceed if so -- testing, documentation, pull request etc. And thanks @jbathegit  for looking into it - I couldn't have worked out a solution without your explanations!

**Comment by jbathegit** [comment]
Hi @JackReevesEyre, thanks for the offer, and yes I'd definitely like to take a look at what you have.  I started puttering around with a solution of my own late last week, but it's still in the early stages b/c I was on leave during the first part of this week.  And I'm basically a Python newbie (I'm more of a Fortran and C expert), so I'd definitely appreciate help from someone who's more of an expert, and maybe we can team up our approaches together into a joint solution.

What I'd suggest is for you to go ahead and start a new working branch in GitHub off of the main `develop` branch and push your changes there.  I can then add in what I have so far as a subsequent commit to that branch (in case there's anything you haven't already figured out yourself ;-), and then we can go forward from there.  Would that work for you?

Please take a look at the python subdirectory off of the main directory to see how our Python binding is currently organized and structured to interface with the Fortran and C parts of the library.  In particular, note the _bufrlib.pyf and ncepbufr/\__init\__.py files which will definitely need to be updated.  We'll also need to include a test case in the python/test subdirectory, either a completely new test program or else a mod to one of the existing ones in order to call the new wrapper function and verify its output.  As the code manager I can certainly help guide you in that process, or if this all ends up being too "down in the weeds" for you, then no worries and I'll be happy to just take whatever you have and build on it myself from there.  Just let me know.

And just FYI, I'll be out of the office tomorrow but can resume with this task either on Friday or early next week.

**Comment by JackReevesEyre** [comment]
Thanks @jbathegit -- I have created a branch in my fork (https://github.com/JackReevesEyre/NCEPLIBS-bufr/tree/jre_py_long_strings). I could do with some help on the pull request from there though. Also, what's the protocol for getting additional testing data added to the zip archive that is downloaded for the test suite? I would need to add a new file there (~ 3 MB).

**Comment by jbathegit** [comment]
Thanks @JackReevesEyre.  What you have looks pretty good, and I just have a few minor suggestions/quibbles:

- It's up to you, but IMO allowing as many as 120 characters for chr in _bufrlib.pyf is probably overkill.  BUFR isn't efficient at compressing long character strings unless they're identical across all subsets in a BUFR message, so as a result you don't typically see too many really long character strings in BUFR.  I think the longest one I've ever seen is around 64 characters, so that's what I set as the maximum in my version of _bufrlib.pyf.  But again, not a big deal and it should still work fine if you want to keep it at 120 characters.  Just my $0.02.
- In my version of \__init\__.py, I included the following additional sentence in my docblock for read_long_string, because it's an important feature of the underlying readlc routine, and so I'd suggest to add it into your docblock as well for the benefit of future Python users of this routine:  `If the subset contains more than one occurrence of the mnemonic, then can append '#X' to the mnemonic to request the character string corresponding to the Xth occurrence of the mnemonic, counting from the beginning of the subset.  Otherwise, X is assumed to be 1.`
- In your test.py updates, I noticed that none of your 5 test_report_ids strings happened to be longer than 8 characters, which makes sense given that RPID is only defined as 8 characters.  So it's not strictly necessary to use read_long_string to retrieve those values, but as you've probably noticed it should still work.  Not a big deal, and as long as each of the 5 test_station_names (i.e. STSN) values are properly retrieved, then I think that's a sufficient test that the read_long_string wrapper is working properly.

I can take care of adding your new xx103 test file to the zip archive.  If it's only 3 Mb you may(?) be able to attach it to this thread, or you can email it to me separately and I'll get it added for you.  If you want, you can then go ahead and submit a PR yourself, and just include `Fixes #226` as the first line of the description box for your PR, in order to link it to this issue.  You can then request me as a reviewer, and if all looks good I can approve and get it merged into the main branch for you.  At that point it would become part of the next future release.

Speaking of which, I'm going to be doing a mini-release in the next day or two (as version 11.7.1) for another user who needs a new feature sooner rather than later.  Along those lines, how soon do you need this particular new read_long_string feature available in a release version?  If you need it fairly soon, and if we can get this wrapped up quickly, then I can include it in the new mini-release; otherwise, I'm not expecting to do another future release until late November or early December.

Please let me know, and either way thanks a lot for taking the initiative to develop a solution for this!

**Comment by JackReevesEyre** [comment]
I don't need the feature in a release right away, but if it can still get into the mini-release, then great. I've made the changes you suggested on the maximum string length and documentation. (I thought I had seen a character length specification of 120 somewhere in the Fortran code, but I can't find it now so I guess I was mistaken! 64 characters is plenty for my purpose.) I've left the test as is. I'll submit the pull request shortly. I'll email the test data file to you as well.
