### ISSUE TITLE
new release 11.7.1

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/NCEPLIBS-bufr#227]
What needs to be done:

- increment number in VERSION file
- update release notes, in both GitHub and in ReleaseNotes.md
- generate docs and update gh-pages branch with the new html

@rmclaren @srherbener just to clarify, and now that PR #222 has been merged, you are requesting this new mini-release, correct?

If so, then I'll work on the above housekeeping tasks and get this released for you.  Once I've done that, I'll let you know, and then you can proceed with https://github.com/NOAA-EMC/spack-stack/issues/289

But first, and again, please confirm that the develop branch now has everything you need for JEDI - thanks!

**Comment by rmclaren** [comment]
@jbathegit Yes, thanks Jeff! I ran it against my branch that uses the type information.  We will need the tag in order to properly deploy the new version of NCEPLIB-bufr.

**Comment by srherbener** [comment]
@jbathegit, @rmclaren Thank you for getting this patch (mini-release) tested and prepared! I'm good to go as long as Ron okays it (which it sounds like he has done already).
