### ISSUE TITLE
rename all moda*.F files as moda*.f90

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/NCEPLIBS-bufr#233]
Since all builds of the library now use dynamic allocation by default (as of v11.6.0+), then the moda*.F files no longer contain any pre-processing code since that time, and therefore these same files no longer need to be run through the pre-processor during the build step.  Renaming these files to moda*.f90 will automatically bypass the pre-processor for these files during the build step.

As a side note, the only Fortran library files which still contain any pre-processing code, and which therefore still need to be run through the pre-processor during the build step, are irev.F and wrdlen.F

**Comment by edwardhartnett** [comment]
You may wish to save a step and rename them to .F90.

In other NCEPLIBS projects we have renamed all fortran files to *.F90. This
allows us to use the pre-processor anywhere. Using the preprocessor is very
helpful when building portable code. For example if you want to handle
ip-4.0.0 and previous versions of ip, you can set a pre-processor flag in
CMakeLists.txt, and then in your code use an #ifdef around the use
statement.

**Comment by edwardhartnett** [comment]
Jeff, can we do this now?

This will change the doxygen formatting slightly, and for the better. When processing f90 code, doxygen does a better job of assigning types to parameters. Also the f90 comment style works more cleanly because not everything has to be indented 7 columns.

**Comment by jbathegit** [comment]
Adding @jack-woollen for his input.

I'm OK with this in principle if it's just a name change for now, i.e. just renaming all of the existing .f files as F90, but still leaving them as fixed-format, for now at least.  But if what you're suggesting also involves painstakingly going through hundreds of existing .f routines to actually change all of them to be F90 free-format (e.g. changing all continuation lines from a `.` in column 6 to a `&` at the end of the line), then I have to question whether this is really a good use of our limited time vs. just a "nice to have"?

As I noted in #261, my next big task is to finish modernizing the rest of the C-Fortran interface in the library (#79), so I for one won't have any time to devote to this anytime soon.

**Comment by edwardhartnett** [comment]
With an emacs macro, the continuation lines can be changed in one operation per file.

However, I will withdraw the suggestion. Let's get the doxygen problems all sorted out first...
