### ISSUE TITLE
update yaml file to use macos-11 instead of soon-to-be-deprecated macos-10.15

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/NCEPLIBS-bufr#235]
macos-10.15 will no longer be available in the GitHub runner as of 12/1/2022.

See https://github.com/actions/runner-images/issues/5583 for more details.

**Comment by jbathegit** [comment]
@edwardhartnett @aerorahul @Hang-Lei-NOAA @AlexanderRichert-NOAA

I just tried to push an update on a new update/yaml branch to fix this issue for NCEPLIBS-bufr.  But I'm getting the following error:
```
! [remote rejected] update/yaml -> update/yaml (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/main.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/noaa-emc/nceplibs-bufr'
```
So I'm guessing this means I don't have the necessary permissions in my jbathegit GitHub account(?)  This probably goes all the way back to when NCEPLIBS-bufr was first moved over to GitHub and configured there.  In any case, I'd appreciate any help or guidance to resolve this - thanks!

**Comment by AlexanderRichert-NOAA** [comment]
I think that's an authentication issue, not an issue with the repository per se. It seems that whatever access token you're using to access git does not include the right permissions for creating/updating a workflow.

**Comment by Hang-Lei-NOAA** [comment]
Now github use a token with your username to push the commit, instead of password.

**Comment by jbathegit** [comment]
> I think that's an authentication issue, not an issue with the repository per se. It seems that whatever access token you're using to access git does not include the right permissions for creating/updating a workflow.

I only have one access token that I know of.  It's the one I've always used to push any updates to GitHub.  So how could we go about fixing this?  Or should I rely on others to update these yaml files whenever we need to make a change like this to the workflow?

**Comment by jbathegit** [comment]
> Now github use a token with your username to push the commit, instead of password.

Yes, I was using my token and not my password.  But it still generated this error.  Again, I only have one access token.

**Comment by AlexanderRichert-NOAA** [comment]
Can you verify that the token has the "workflow" scope enabled by going to https://github.com/settings/tokens and clicking on the token name?

**Comment by Hang-Lei-NOAA** [comment]
@jbathegit I saw it. You are moved out of NCEPLIBS team. I just invite you again.

**Comment by Hang-Lei-NOAA** [comment]
@AlexanderRichert-NOAA I try to add you, but it is denied for that you are not a EMC member. You have to first become a EMC memebr. I not sure how to get that step.

**Comment by AlexanderRichert-NOAA** [comment]
It says I'm a member of "NOAA-EMC", is that not sufficient?

**Comment by Hang-Lei-NOAA** [comment]
I don't know. The system say that you are not, and I cannot operate. You may have to get other permission.

**Comment by jbathegit** [comment]
> Can you verify that the token has the "workflow" scope enabled by going to https://github.com/settings/tokens and clicking on the token name?

OK, I just updated my token to add the "workflow" scope and was able to push my change.  Thanks @AlexanderRichert-NOAA , and thanks too to @Hang-Lei-NOAA for your help!

**Comment by edwardhartnett** [comment]
Alex has just been added to NOAA-EMC, so any problems in that regard will hopefully go away.

WRT the CI for MacOS, can you switch to macos-latest as the version? This keeps the version moving forward with macos releases, which is what we want.

This introduces problems, as the macos build seems to be less stable than the ubuntu build, not sure why. But keeping up to date with the latest is what we need to do, even if it's a pain.

(See https://github.com/ufs-community/UFS_UTILS/issues/712)
