### ISSUE TITLE
Continue: Error: BUFRLIB: NEMTBD - REPLICATOR IS OUT OF ORDER IN TABLE D SEQUENCE MNEMONIC MSTTB001

### ISSUE THREAD

**Issue by LucaFibbi** [NOAA-EMC/NCEPLIBS-bufr#248]
This issue is a continuation of the issue #234 that it is be closed.
I agree with the considerations of the development teams of libbufr:
the descriptor '031001' is illegal in any context other than immediately
following a '1XX000' descriptor. The BUFR message shouldn't contain
this type of descriptor without a precedent '1XX000' descriptor.
But BUFR message with this type of problem are continuing to arrive from
'RKSL' originator centre and they seem to contain plausible meteorological
data if decoded with other software how bufr_dump program of ecCodes 
package developed by ECMWF.
I have find a solution for remove the error and decode the BUFR message
with this problem how bufr_dump program do.
Here the patch:
`--- nemtbd.f	(revision 808)
+++ nemtbd.f	(working copy)
@@ -119,8 +119,14 @@
 
 C            Replication factor.
 
-         IF(.NOT.REP) GOTO 904
-         IRPS(NSEQ+1) = IRET
+         IF(REP) THEN
+            IRPS(NSEQ+1) = IRET
+         ELSE
+            CALL NUMTBD(LUN,IDSC,NEMT,TAB,IRET)
+            IF (IRET.LE.0) GOTO 905
+            NSEQ = NSEQ+1
+            NEMS(NSEQ) = NEMT
+         ENDIF
          REP = .FALSE.
       ELSEIF(TAB.EQ.'D'.OR.TAB.EQ.'C') THEN
          REP = .FALSE.
`
I hope it can be useful.

**Comment by LucaFibbi** [comment]
I attach the file with the  changes and the patch because the the tesx in the issue comment not is readable.
[nemtbd.zip](https://github.com/NOAA-EMC/NCEPLIBS-bufr/files/10196019/nemtbd.zip)

**Comment by jbathegit** [comment]
Hello @LucaFibbi.  While I appreciate the effort on your part, I still don't believe this is something for which we should install a special patch/workaround in the library.  The real solution would be for RKSL or any other data provider to fix the problem on their end and stop disseminating messages with illegal coding constructs.  Again, this is a pretty significant violation of the rules of BUFR.
