### ISSUE TITLE
README.md in utils directory should be added to doxygen docs

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#26]
README.md in utils directory should be added to doxygen docs

**Comment by jbathegit** [comment]
Just curious - why do we need to do this?  The contents of README.md already show up in the https://github.com/NOAA-EMC/NCEPLIBS-bufr - do we want it to be displayed somewhere else as well?

**Comment by edwardhartnett** [comment]
This is the README in the utils directory, which contains some documentation about utils...
