### ISSUE TITLE
program utils/binv.f90 and other programs in the utils directory have zero documentation

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#262]
In other NCEPLIBS projects we had a lot of legacy documentation to convert, but everything was documented.

In NCEPLIBS-bufr we have programs, subroutines, and modules that don't have a single line of documentation to bless themselves with.

@jack-woollen and @jbathegit the program utils/binv.f90 was written and is maintained by you guys. I can see from the history that it was added two years ago by Jeff, and updated 10 months ago by Jack. At both those times, there was a documentation standard in place. Two years ago it was the legacy standard - 10 months ago it was the improved doxygen standard. Both require that all programmers document all code.

Yet no documentation was ever added. Are documentation requirements not clear?

How come no documentation was even attempted? What is going on with utils/binv.f90?

**Comment by jack-woollen** [comment]
@edwardhartnett @jbathegit I'll definitely get on this, and help out with the other stuff,  in the next couple days. This last couple weeks have been extremely busy with various other projects coming to a head.

**Comment by edwardhartnett** [comment]
OK, there has been a lot of progress. But utils/readbp.f90 is still undocumented.

**Comment by edwardhartnett** [comment]
Looks like all these have been fixed. I will close this issue.
