### ISSUE TITLE
Lots of new warnings like Warning: Nonconforming tab character in column 1 of line 35 [-Wtabs]

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#272]
Where are these coming from?

```
cd /home/ed/NCEPLIBS-bufr/b/src && /usr/bin/gfortran -DLITTLE_ENDIAN -I/home/ed/NCEPLIBS-bufr/b/src -I/home/ed/NCEPLIBS-bufr/src -g -fbacktrace -ggdb -Wall -O0 -Jinclude/bufr_4 -fPIC -c /home/ed/NCEPLIBS-bufr/src/iupbs3.f -o CMakeFiles/bufr_4_f.dir/iupbs3.f.o
f951: Warning: Nonconforming tab character in column 1 of line 35 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 37 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 39 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 41 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 48 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 49 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 51 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 53 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 54 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 55 [-Wtabs]
f951: Warning: Nonconforming tab character in column 2 of line 57 [-Wtabs]
f951: Warning: Nonconforming tab character in column 2 of line 58 [-Wtabs]
f951: Warning: Nonconforming tab character in column 2 of line 59 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 61 [-Wtabs]
f951: Warning: Nonconforming tab character in column 2 of line 63 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 65 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 66 [-Wtabs]
f951: Warning: Nonconforming tab character in column 2 of line 68 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 70 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 71 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 72 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 73 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 74 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 75 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 76 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 77 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 78 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 79 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 80 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 81 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 82 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 84 [-Wtabs]
f951: Warning: Nonconforming tab character in column 1 of line 85 [-Wtabs]
/home/ed/NCEPLIBS-bufr/src/iupbs3.f:39:16:

   39 |  DIMENSION MBAY(*)

      |                1
Warning: Nonconforming tab character at (1) [-Wtabs]
/home/ed/NCEPLIBS-bufr/src/iupbs3.f:41:20:

   41 |  CHARACTER*(*) S3MNEM
      |                    1
Warning: Nonconforming tab character at (1) [-Wtabs]

```

**Comment by edwardhartnett** [comment]
OK, I have learned that the TAB character is actually not part of the fortran standard and gfortran, when run with -Wall, will flag tab characters.

These are not new warnings, just new to me. ;-)

The easy answer is to replace tabs with spaces. Emacs includes the function M-x tabify which does this, and I can apply this function to the whole set of bufr files in one operation.

However, this would mean that @jack-woollen and @jbathegit would have to get used to code with spaces not tabs. In emacs, the tab key does the correct thing when settings are correct, working like a tab key but adding spaces instead. I don't know what editor you guys use, but probably it has similar functionality.

Here's some websites that discuss the problem:
https://stackoverflow.com/questions/31987331/silence-the-warning-non-conforming-tab-character-in-gfortran
https://forums.approximatrix.com/viewtopic.php?id=85

Note that using -Wall and writing warning free code is a very powerful quality tool that most projects would not willingly live without for the sake of a TAB character. -Wall finds many real bugs, and we want to be able to run a warning-free build of NCEPLIBS-bufr with -Wall in the CI. It seems like a distant goal, but it is not hard, and helps a lot.

**Comment by jbathegit** [comment]
I use the vi editor, and while I can't speak for @jack-woollen, I'm personally fine with replacing all tabs with spaces if it gets us to a good place of warning-free code, and especially if you know of an emacs trick or other macro which does this automatically throughout one or more files.

And going forward, I'll just need to get myself in the habit of always using the spacebar to indent, especially when I'm editing after copying+pasting other existing lines of code.  So add this to the list, I guess ;-)

**Comment by edwardhartnett** [comment]
I'm sure that vi has a way to change the meaning of the tab key to insert spaces instead of a tab character. See here for example: https://vi.stackexchange.com/questions/4141/how-to-indent-as-spaces-instead-of-tab

**Comment by edwardhartnett** [comment]
After we finish documentation, I would like to clear up warnings next.

The warnings described in this issue are easy to fix, and I am happy to do that. But meanile, @jbathegit and @jack-woollen you guys need to switch your editors to using only spaces. Here's a description of how to change to spaces with vi and vim: https://vi.stackexchange.com/questions/4141/how-to-indent-as-spaces-instead-of-tab

If you are using emacs, you put this in your .emacs file to use spaces instead of tabs everywhere:
(setq-default indent-tabs-mode nil)

Can you guys please make this change? Then I will fix the existing tabs in the code...

**Comment by jbathegit** [comment]
Yes, I've already gotten in the habit of doing that, by just using the space key instead of the tab key.  I'm fully on board with this going forward, and as you said we just need to remove all of the existing tabs from the current source files.
