### ISSUE TITLE
special doxygen woes - two problem files are breaking doxygen build

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#277]
In addition to the normal doxygen warnings, we have these:

```
********************************************************************
Error in file /home/ed/NCEPLIBS-bufr/utils/cmpbqm.f90 line: 124, state: 22(String)
********************************************************************

```
and 

```
********************************************************************
Error in file /home/ed/NCEPLIBS-bufr/b/utils/sinv.f90 line: 123, state: 22(String)
********************************************************************

```

These two files are confusing the doxygen parser. Something needs to change in them...

**Comment by edwardhartnett** [comment]
OK, what was confusing doxygen was a *.f90 file, formatted like a *.F file.

That is, F77 formatting in f90 file confuses doxygen.

By running the three emacs commands on this file:
M-x indent-region
M-x untabify
M-x delete-trailing-whitespace

I cleaned up the formatting of the file without making any code changes. This now allows doxygen to work on these files.

**Comment by jack-woollen** [comment]
@edwardhartnett  where do these errors show up. I don't see them in the logs.

**Comment by edwardhartnett** [comment]
They will only show up in the developer build, since that's the only one that builds the documentation.

You can also see them by building on your own machine.

**Comment by edwardhartnett** [comment]
These problems are resolved now on develop branch. I will close this issue.
