### ISSUE TITLE
deprecated commands in workflows

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/NCEPLIBS-bufr#303]
If you drill down into the output of the CI tests for any of the workflows, and then click on the "Summary" button and scroll down, you'll see the following warnings for some commands that are now deprecated.

![deprecated commands](https://user-images.githubusercontent.com/62722702/214434824-3ad04ad2-80ff-4639-a9dd-9be65c9f7323.PNG)

Viewing the URL link in a browser, it looks like we have until May before the commands become invalid and cause our CI tests to fail.  I presume this is something we need to change in our yaml files, but I didn't see any `save-state` or `set-output` references in any of those files, so now I'm not sure I understand what we need to do here.  @edwardhartnett or @AlexanderRichert-NOAA, any ideas?

**Comment by edwardhartnett** [comment]
Don't worry about it. There are various warnings like this from the CI system, but they've never caused problems.
