### ISSUE TITLE
Cause tests to fail with non-zero return code

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#308]
This can be very easily accomplished by inserting a stop command after every error message.

**Comment by jbathegit** [comment]
Since you've been working on the IN codes, I'm going to start working on the OUT codes so we don't step on each others toes.

**Comment by jbathegit** [comment]
But here's the thing - the OUT tests are writing BUFR output to test the output side of the library.  And the way each of those tests works is that there are few, if any, stops inside of the code, and instead the full test can't be judged a success or failure until it has run through completely and the resulting output is then compared (using `cmp -s` or similar command in a UNIX shell wrapper) to an expected baseline result to confirm it matches the expected output.  So how do we replicate that functionality inside of the code if all we're looking at is the return code to gauge success or failure?

**Comment by jbathegit** [comment]
I've been snooping around for ideas, and it seems like there's now a `call execute_command_line()` intrinsic that can be called from inside of Fortran, at least as of the Fortran 2008 standard.  It's modeled on the old `system()` function in C, and it can return the exit status of a shell command (e.g. from 'cmp -s') as argument exitstat right within the flow of the code, as long as it isn't allowed to run asynchronously.

So it seems like that might do the trick, unless you know of any potential drawbacks or can think of anything I may be missing here(?)

**Comment by jbathegit** [comment]
The `execute_command_line()` intrinisic worked great, so now we have an easy way forward for all of the OUT tests.  I've just completed the transitions for OUT_1 and OUT_2, and I'll continue with the remaining ones tomorrow.

**Comment by edwardhartnett** [comment]
Great to see this accomplished and the test situation simplified.
