### ISSUE TITLE
Unit tests for src/copybf.f, src/copymg.f, src/copysb.f, src/cpbfdx.f, src/cpdxmm.f, src/cpymem.f, src/cpyupd.f 

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#33]
src/copybf.f, src/copymg.f, src/copysb.f, src/cpbfdx.f, src/cpdxmm.f, src/cpymem.f, src/cpyupd.f are all untested

**Comment by jbathegit** [comment]
I think I can cover src/cpbfdx.f within a new test program that I'm currently working on for #51, #52, #53, and #54.

**Comment by edwardhartnett** [comment]
Codes with apparently zero testing include:

1. bort and it's variants.
2. copybf
3. cwbng
4. dlloctbf
5. drstpl
6. invmrg
7. mesgbf
8. mrginv
9. nevn
10. newwin
11. nwords
12. openbt
13. trybump
14. ufbcpy
15. ufbcup
16. ufbget
17. ufbin3
18. ufbinx
19. ufborv
20. ufbtam

So if these codes are important, they need to be tested.

If they are not, they need to be removed. ;-)

Getting at least a few tests for each subprogram should be a top priority unless there are urgent bugfixes or new releases that need to get out to users...

These tests should be written in the style of intest1.F90:
* They should all be *.F90 codes.
* They should return non-zero for an error, and exit normally for success.
* Scanning of the output is not necessary, so in CMakeLists.txt these are just ordinary Fortran test programs that are compiled and run, just like intest1.
* They should be well-documented as to what they are, and what they are trying to do.

**Comment by jbathegit** [comment]
With #331 we now have coverage for the following subprograms from the above list:

- 2 (copybf)
- 3 (cwbmg)
- 4 (dlloctbf)
- 7 (mesgbf)
- 14 (ufbcpy)
- 16 (ufbget)
- 18 (ufbinx)
- 20 (ufbtam)

**Comment by jbathegit** [comment]
With the latest updates to #331 we now also have coverage for:
- 6 (invmrg)
- 8 (mrginv)
- 9 (nevn)
- 11 (nwords)
- 13 (trybump)
- 17 (ufbin3)
- 19 (ufbovr)

**Comment by edwardhartnett** [comment]
@jbathegit here's a question about copymg.

If I run this code:

```
        open(unit = 11, file = 'testfiles/IN_2', form = 'UNFORMATTED', iostat = ios)
        if (ios .ne. 0) stop 3
        call openbf(11, 'IN', 12)
        call openbf(12, 'OUT', 13)
        call copymg(11, 12)     

```

I get this error:

 ```
***********BUFR ARCHIVE LIBRARY ABORT**************
 BUFRLIB: COPYMG - A MESSAGE MUST BE OPEN IN INPUT BUFR FILE, NONE ARE
 ***********BUFR ARCHIVE LIBRARY ABORT**************

```

OK, the documentation had the answer!

Now I have:

```
        open(unit = 11, file = 'testfiles/IN_2', form = 'UNFORMATTED', iostat = ios)
        if (ios .ne. 0) stop 3
        call openbf(11, 'IN', 11)
        call readmg(11, char_val_8, jdate, iret)

```
And it finds a message. ;-)

**Comment by edwardhartnett** [comment]
I am taking a pass though these functions to see if bort testing can be improved.

Here's the current testing levels for these functions:

Function | Coverage
------------|--------------
copybf | 100
copymg | 77
copysb | 68
cpbfdx | 100
cpdxmm | 63
cpymem | 79
cpyupd | 50

These numbers will improve slightly when #415 is merged.

**Comment by edwardhartnett** [comment]
Here's the current testing levels for these functions:

Function | Coverage
------------|--------------
copybf | 100
copymg | 91.4
copysb | 78.9
cpbfdx | 100
cpdxmm | 63
cpymem | 79
cpyupd | 50

So some improvement, but still more testiing needed.

**Comment by edwardhartnett** [comment]
Here's the current testing levels for these functions:

Function | Coverage
------------|--------------
copybf | 100
copymg | 91.4
copysb | 84.2
cpbfdx | 100
cpdxmm | 70
cpymem | 79
cpyupd | 93

Seems like there are some error conditions in cpymem() and cpdxmm() that could be tested. However, overall, what a great improvement.

**Comment by jbathegit** [comment]
Following the merging of some recent PRs, cpdxmm is now at 91% and cpymem is now at 97%.  So I think we can close this one now.

**Comment by edwardhartnett** [comment]
Nice!
