### ISSUE TITLE
Extract Tank Receipt Time from section 1 of the BUFR message

### ISSUE THREAD

**Issue by emilyhcliu** [NOAA-EMC/NCEPLIBS-bufr#333]
For DA application, we will need to know when the data is available for DA. 
BUFR message section contains such information.  It is called "Tank Receipt Time".  

"Tank Receipt Time" ([rtrcpt](https://noaa-emc.github.io/NCEPLIBS-bufr/rtrcpt_8f.html#af1b460e0604b1216d2385b7f2a0f2f7d))
```
Found BUFR message #    359
        Message length:         850
      Section 0 length:           8
          BUFR edition:           3

      Section 1 length:          18
          Master table:           0
    Originating center:           7 (= U.S. National Weather Service, National Centres for Environmental Prediction (NCEP))
 Originating subcenter:           3 (= NCEP Central Operations)
 Update sequence numbr:           0
    Section 2 present?: No
         Data category:           2 (= Vertical soundings (other than satellite))
     Local subcategory:           5 (= PIBAL)
 Internatl subcategory:          -1
  Master table version:          29
   Local table version:           0
                  Year:        2020
   `
              Month:          11
                   Day:           1
                  Hour:          11
                Minute:           0
                Second:          -1
 Number of data subsets:           2
     Data are observed?: Yes
   Data are compressed?: No
  Number of descriptors:           6
        1: 063000
        2: 363222
        3: 102000
        4: 031001
        5: 206001
        6: 063255
BUFR message #    359 of type NC002005 and date 2020110111 contains      2 subsets:
```

**Comment by jbathegit** [comment]
Just so everyone's aware, tank receipt time isn't in any BUFR message by default.  Rather, it's only there if the application which generated the message made a call to [subroutine strcpt](https://noaa-emc.github.io/NCEPLIBS-bufr/strcpt_8f.html) to store it there during the time that the message was being generated.  This is usually the case for messages in tank files that were generated via the bufr_tranjb application, but again I just wanted you to be aware that there may be some tank files out there where this isn't the case.

**Comment by jbathegit** [comment]
I never heard anything further about this.  Is this still an active issue, or can this be closed?

**Comment by jbathegit** [comment]
Closing due to lack of feedback
