### ISSUE TITLE
add test for SUBROUTINE NEWWIN.f

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#342]
This subroutine is currently untested.

**Comment by edwardhartnett** [comment]
@jack-woollen can you give some guidance on how this test should work?

**Comment by jack-woollen** [comment]
@Edward Hartnett - NOAA Affiliate ***@***.***>
  I attached a piece of code to test newwin. It sets up a file read,
locates a replicated sequence in the data and cycles newwin through the
number of replications in the sequence. It prints a list of array locations
for each replication, which can be checked against the baseline data.

! subroutine newwin identifies the next segment of a replicated sequence.
Newwint will test that operation.
      program newwint

      USE MODA_USRINT
      USE MODA_TABLES

      character*8 subset
      character*1 go
      real(8) ncdt(5,50)
      COMMON /USRSTR/ NNOD,NCON,NODS(20),NODC(10),IVLS(10),KONS(10)

! open a file and read the first message and subset
      call openbf(20,'IN',20)
      do while(ireadmg(20,subset,idate).eq.0)
      do while(ireadsb(20).eq.0)
      print*,subset,' message date=',i4dy(idate)
      call ufbint(20,ncdt,5,50,iret,"RCYR RCMO RCDY RCHR RCMI")
      print'(5(f5.0))',ncdt(:,1:iret)

! setup the window environment
      lun=1
      ins1=1
      ins2=nval(lun)

! cycle through the windows of the replicated sequence
! the output can be tested against stored answers
      do n=1,nnod
      print*,tag(nods(n)),iret
      if(tag(nods(n))=='RCHR') then
         iwin = jmpb(nods(n))
         do m=1,iret
         print*,iwin,jwin
         call newwin(lun,iwin,jwin)
         iwin=jwin
         enddo
         exit
      endif
      enddo
      stop

! end of read loops - end of program
      enddo
      enddo
      end program

**Comment by jack-woollen** [comment]
@edwardhartnett Let's backup a little. What I sent in response to your question was an example of how newwin worked, as some guidance as to how it can be tested.  First, thanks for the questions which I'll partially answer to begin with. Newwin is simple but needs context to operate. It operates on data read from a subset into a subset buffer. A subset buffer consists of two arrays in module  moda_usrint called inv and val. These contain information determining how many 'windows' are in the subset. Some have only one, some have many. Newwin  locates a subset buffer which has been input from file handle lun. It looks at index iwin in the buffer to see where the end of the window starting at iwin is, and returns that index as jwin. That's all it does. This is a very abstract view. To see more context we need subroutine ufbrw, which manages the operation of newwin and the whole ---win family of buffer interrogators, which consists of conwin.f  getwin.f  invwin.f  newwin.f  nvnwin.f  nxtwin.f. This set of subroutines basically parses subset contents looking for user requested data elements from an input file, or looking for where to put user specified data elements into an output file. 

Without getting too deep in the weeds and not getting anywhere, I think the solution to this is to write tests for ufbrw which can rattle the cages on the whole family of codes listed. I actually think this is effectively done across the array of tests already in place. If any of these functions were failing you would see errors in some or all of those tests, without a doubt. Ufbrw is the forest. All the components are trees or bushes or whatever. I think you have to start at the forest level to understand what kind of additional testing of this complex of routines makes sense.  I can work on this in turn with my 2 or 3 other high priority projects. My number 1 first priority for the rest of this week is taking the time I need to deal with a + covid test I got this weekend after returning from a funeral last weekend near Charlotte NC. This is about as much work as I can do on this for the time being.

**Comment by edwardhartnett** [comment]
I will close this issue, since we now have some testing for this code. Thanks @jack-woollen and @jbathegit for getting this code under testing.

In response to the discussion above: we need testing for both the trees (unit testing) and the forest (system testing).

The recent example of cread.c tests illustrates the reason: system level tests already tested cread.c, but when I added unit tests, we still found some bugs. System level testing is great and necessary, but unit level testing is better for testing all code pathways, error conditions, and the testing of different parameter values.

In addition, bugs are usually a lot easier (i.e. faster) to find and fix when they are detected in unit testing. When a bug occurs in system testing, often there is a lot of work figuring out exactly where in the system the problem occurs. With unit testing, that's usually very obvious.

Since we are retrofitting tests, we can focus on system testing first. But for all new code introduced to the library, we will want to  ensure that it has good unit tests, as well as good system testing.
