### ISSUE TITLE
complete testing for arallocf.f

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#346]
I don't understand what the untested code is doing. Is this error handling?

**Comment by jbathegit** [comment]
No, this is just printing out what the all of the configurable parameter settings are, whenever the user has verbose output logging set via a prior call to openbf() with IO='QUIET' and LUNDX>0.

**Comment by edwardhartnett** [comment]
OK, so this can be tested.

**Comment by edwardhartnett** [comment]
This code remains untested:
        IF ( IPRT .GE. 1 ) THEN
            CALL ERRWRT
     .          ('++++++++++++++BUFR ARCHIVE LIBRARY+++++++++++++++++')
            ERRSTR = 'BUFRLIB: ARRAYS WILL BE DYNAMICALLY ALLOCATED' //
     .          ' USING THE FOLLOWING VALUES:'
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I7)' ) '    MAXSS = ', MAXSS
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I4)' ) '   NFILES = ', NFILES
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I7)' ) '   MXMSGL = ', MXMSGL
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I5)' ) '   MXDXTS = ', MXDXTS
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I7)' ) '   MAXMSG = ', MAXMSG
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I9)' ) '   MAXMEM = ', MAXMEM
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I5)' ) '   MAXTBA = ', MAXTBA
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I5)' ) '   MAXTBB = ', MAXTBB
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I5)' ) '   MAXTBD = ', MAXTBD
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I7)' ) '    MAXJL = ', MAXJL
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I6)' ) '    MXCDV = ', MXCDV
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I4)' ) '    MXLCC = ', MXLCC
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I6)' ) '    MXCSB = ', MXCSB
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I5)' ) '   MXMTBB = ', MXMTBB
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I5)' ) '   MXMTBD = ', MXMTBD
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I4)' ) '    MAXCD = ', MAXCD
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I4)' ) '    MXNRV = ', MXNRV
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I4)' ) '   MXS01V = ', MXS01V
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I4)' ) '   MXTAMC = ', MXTAMC
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I4)' ) '    MXTCO = ', MXTCO
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I4)' ) '    MXBTM = ', MXBTM
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I4)' ) '  MXBTMSE = ', MXBTMSE
            CALL ERRWRT(ERRSTR)
            WRITE ( ERRSTR, '(A,I4)' ) '    MXRST = ', MXRST
            CALL ERRWRT(ERRSTR)
            CALL ERRWRT
     .          ('++++++++++++++BUFR ARCHIVE LIBRARY+++++++++++++++++')
        END IF

Seems like this should be easy to test. Just get the output and make sure it exactly matches some copy of the output you've already captured.

If one of these default values change, it will break the test. That's what we want.

**Comment by edwardhartnett** [comment]
Ah ha! I was looking at an old code coverage report.

When I look at a current one, I see this code is 100% covered in testing. Excellent work!
