### ISSUE TITLE
can we remove or greatly simplify strnum.f?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#369]
We have strnum.f. It says:

```
C> This subroutine decodes an integer from a character string.  The
C> string should contain only digits and (optional) trailing blanks.
C> It should not contain any sign ('+' or '-') character nor any
C> leading blanks nor embedded blanks.

```
Can this not be done with standard fortran in a single command? Why do we have a subprogram for this?

**Comment by jbathegit** [comment]
There's no single standard Fortran command that I've ever seen which does this.  But in #406 I was able to greatly simplify and modernize both strnum and strsuc (and convert them to F90), and I also removed the duplicated functionality in valx.

**Comment by edwardhartnett** [comment]
I believe there is still more to discuss here, so I will reopen this issue. But before discussing it, let's resolve #407.
