### ISSUE TITLE
complete testing for rdbfdx.f

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#370]

**Comment by edwardhartnett** [comment]
This file is now almost fully tested, the only untested parts could conceivably be tested with bad input files. But I'm going to close this issue, as these are hard-to-reach error conditions. If they can be tested at a future time, great. But this subroutine is now pretty well tested.

@jbathegit shall I close this issue and others like it?

**Comment by jbathegit** [comment]
Yes, I think this and other similar issues can now be closed.  As already noted, this doesn't mean that we won't continue to improve testing all throughout the library where and when we can.
