### ISSUE TITLE
passing out of range LUN in string() and some other subroutines causes segfaults

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#384]
In string.f we have:

```
      SUBROUTINE STRING(STR,LUN,I1,IO)

...
      NXT = 0
      UST = STR
      IND = INODE(LUN)

```

What happens if LUN is out of range of INODE or if INODE has not been allocated? Segfaults!!

BTW to test this run the following code:

        call STRING('0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789', &
             1, i1, 0)

**Comment by jbathegit** [comment]
Adding @jack-woollen to this conversation for his awareness, but for my part I'll start out by pointing out that string() isn't a routine that should ever be called directly from an application program.  It's one of those routines that should only ever be called internally from one of the other user-callable library routines.

To put it another way, if we're going to try throwing crazy input at every routine in the library, then we'll likely see a lot more such errors besides this one.  And most of them have internal safeguards in place to prevent such a call from ever occurring in the first place - for example, ufbint() already has an internal check that the value of LUN is valid before it internally calls string().

**Comment by edwardhartnett** [comment]
Speaking generally, one other projects (including netcdf and the other NCEPLIBS) I will always check the inputs to all functions as much as they can be checked, whether internal or external. 

The only difference is that for internal functions where I'm sure that I have full control of inputs, I might use an assert() to test, instead of an if-statement. For example:
```
int
nc4_type_free(NC_TYPE_INFO_T *type)
{
    int i;
    assert(type && type->rc && type->hdr.name);
```

But I always check every parameter as much as possible. A bug in another NCEPLIBS-bufr function could cause this one to be called with incorrect parameters. In which case, we want the subroutine to immediately fail and let us know about the bug.

We have a lot going on right now, and this is not urgent, so I will close this issue and we will circle around to it again in the future.

For now, consider doing full parameter checking for every function, for all new and newly modified code.

**Comment by edwardhartnett** [comment]
Subroutines nemtbb() and nemtbd() suffer from this. When called, it attempts to use the first parameter (LUN) as the index to arrays that may not yet be allocated, and this causes a segfault. Instead, the subroutine should check whether the arrays exist before trying to use them.
