### ISSUE TITLE
Should be in the if-block of ENABLE_DOCS

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/NCEPLIBS-bufr#40]
https://github.com/NOAA-EMC/NCEPLIBS-bufr/blob/b4fde52fc76fbb71db438530549df788b874c4c6/CMakeLists.txt#L72

**Comment by edwardhartnett** [comment]
If you look in the CMake file in the subdirectory you will see that it does nothing if ENABLE_DOCS is not set.

**Comment by aerorahul** [comment]
but, then I have to look underneath.
I saw that.
That directory is docs and should only be included if docs are enabled.
The check inside the doc's directory is redundant.
It places the entire contents of that file in an if-block.  Functional -- yes

**Comment by aerorahul** [comment]
closing because it is addressed in a hidden manner.

**Comment by edwardhartnett** [comment]
Meanwhile, I thought it over more and agree with you. I will fix in all projects...
