### ISSUE TITLE
Incorrect VERSION in tagged version bufr_v11.4.0

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/NCEPLIBS-bufr#41]
bufr_v11.4.0 tag has incorrect VERSION file.
The VERSION file still reads 11.3.1.1

Can someone please update the VERSION file in that tag ASAP?
Downstream projects are using the VERSION from `find_package` to make decisions and the critical version is 11.4.0.

**Comment by aerorahul** [comment]
@edwardhartnett 
Would it be permissible to change the incorrect VERSION in the tag?

**Comment by edwardhartnett** [comment]
Whatever @jbathegit wants to do. It's fine by me to change the VERSION in the tag.

**Comment by aerorahul** [comment]
I will be deleting the tag bufr_v11.4.0 and re-tagging with this branch
https://github.com/NOAA-EMC/NCEPLIBS-bufr/tree/bugfix/version11.4.0

**Comment by aerorahul** [comment]
Fixed via https://github.com/NOAA-EMC/NCEPLIBS-bufr/tree/bugfix/version11.4.0
Closing issue.
