### ISSUE TITLE
combine list_of_files.cmake into CMakeLists.txt

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#42]
It's normal to list all the source code in the CMakeLists.txt file.

I see the impulse to simplify this long list, but putting it in a separate file really doesn't help.

For example, it's typical to do something like:

`find . -name CMakeLists.txt | xargs grep code_file.f
`

to find all the instances of code_file.f in the build system. Putting the list of code files in a separate cmake file just hides it.

**Comment by aerorahul** [comment]
`find . -name `*.cmake` | xargs grep code_file.f`
works too.

**Comment by edwardhartnett** [comment]
By following standard conventions we increase user engagement and ability to contribute to these codes, as well as lowering NOAA support costs and new programmer on-boarding effort.

When we do things differently from everyone else, we introduce unnecessary cost and risk into our code bases.

So in the absence of a strong reason to be different, we will make our build systems similar to community standard practice.

**Comment by aerorahul** [comment]
I like the multi-edged narrative; standard sometimes,  convenience other times and somewhere in between the rest of the time; whatever suits.

**Comment by aerorahul** [comment]
`include()` is a standard way of including files when the list is too long and adds modularity to the `CMakeLists.txt`

**Comment by jbathegit** [comment]
I'm taking a closer look at this one now.

I could certainly move the set() statements for fortran_src, c_src, and c_hdr from `list_of_files.cmake` to `CMakeLists.txt`, but it seems to me an even better solution would be to have `CMakeLists.txt` dynamically generate these lists, rather than having them hardcoded in the file and then having to update the file each time a new source or header file is added, deleted or renamed within the library.   But the downside is that wouldn't allow the use of `find . -name CMakeLists.txt | xargs grep code_file.f` to locate all of the instances of code_file.f, as @edwardhartnett suggested above is a common practice.

Thoughts?

**Comment by edwardhartnett** [comment]
Dynamically generated lists of code files sounds like an unnecessary complication and something that could easily go wrong.

Updating the build system each time a new file is added is normal, and not a heavy burden. Nor do I usually want to include every .h or .inc file in every build. (For example, some .h files will only be needed for compiling tests.) Also, as builds get more advanced, it's not unusual for code files to be included or not, based on the build options.

The point of this issue is to move the build system closer to standard practice, not farther way.

Eliminating the list_of_files.cmake is a good idea: it's an extra artifact that does not simplify anything - since the files have to be listed somewhere, it might as well be in CMakeLists.txt, which is where all users and programmers will expect to find the list of source files. Listing them in a different file simplifies nothing.

Listing the source files in CMakeLists.txt is what everyone else does, so let's just do that.

CMake is not a model of compactness. There's a lot of boilerplate, and a lot of custom cmake code that's required to do things that autotools builds can do automatically. And there are many other things we could complain about as well! But that's the price of using CMake and we are not going to solve CMake problems, we are just going to be happy if we can solve NOAA software problems. ;-)

(And with all it's faults, cmake is very capable and very standard, and a huge advance over home-rolled makefiles.)

The more we innovate in these areas, the harder it is for external users and new programmers to contribute. If we keep to standard practice, we lower the barrier of participation.

**Comment by edwardhartnett** [comment]
I also seem to recall that this code has a convention of one subroutine per file. One thought would be to combine many files into fewer files, if that seems desirable...

**Comment by kgerheiser** [comment]
Globbing files is not recommended:

https://cmake.org/cmake/help/v3.15/command/file.html?highlight=glob#file


"We do not recommend using GLOB to collect a list of source files from your source tree. If no CMakeLists.txt file changes when a source is added or removed then the generated build system cannot know when to ask CMake to regenerate. The CONFIGURE_DEPENDS flag may not work reliably on all generators, or if a new generator is added in the future that cannot support it, projects using it will be stuck. Even if CONFIGURE_DEPENDS works reliably, there is still a cost to perform the check on every rebuild."

**Comment by jbathegit** [comment]
Thanks for the feedback guys, and as suggested I'll go ahead and list everything explicitly in the CMakeLists.txt file.
