### ISSUE TITLE
Add additional value for  CAT in bufrtab.CodeFlag_LOC_0_7_1

### ISSUE THREAD

**Issue by ilianagenkova** [NOAA-EMC/NCEPLIBS-bufr#424]
Code development by @nicholasesposito is adding a new value for the mnemonic CAT in the prepbufr table.
The new CAT value is "10" and needs to go into:
https://github.com/NOAA-EMC/NCEPLIBS-bufr/blob/develop/tables/bufrtab.CodeFlag_LOC_0_7_1#L610

Shall we provide just an updated bufrtab.CodeFlag_LOC_0_7_1 file or a PR is prefered?

@nicholasesposito , please provide (in comments) a suggested title for CAT=10 . Thanks!

**Comment by ilianagenkova** [comment]
@dmerkova , @ChristopherHill-NOAA , tagging you for awareness.

**Comment by ChristopherHill-NOAA** [comment]
The use of the value CAT=10 was first introduced within the obsproc | prepobs development branch [dev.iss49636.TAC2BUFR_upper-air](https://github.com/NOAA-EMC/prepobs/tree/feature/dev.iss49636.TAC2BUFR_upper-air).  Use of this value is also featured within development branch [GPS_NickE](https://github.com/NOAA-EMC/prepobs/tree/feature/GPS_NickE).

CAT=10 represents a vertical level unique to the high-resolution BUFR transmission of an upper-air profile report, and therefore differs from the other previously defined values of CAT.  For simplicity, the following reference of CAT=10 would be appropriate for addition to [bufrtab.CodeFlag_LOC_0_7_1](https://github.com/NOAA-EMC/NCEPLIBS-bufr/blob/develop/tables/bufrtab.CodeFlag_LOC_0_7_1#L610):

 `| 10 |  high-resolution level (upper air profile reports)`

**Comment by jbathegit** [comment]
Thanks for the heads-up, but this doesn't require a PR because the tables are automatically generated from our BUFR tables database on ncointra.  So I just need to add the new entry to the database, and then it will show up automatically in all of the downstream tables the next time I run the generation script.

As a side note, I assume you're aware that entries 8 and 9 are currently vacant in this CAT table?  It's OK if you want to leave those as "Reserved" and skip to using 10 for this new entry - just more of a curiosity than anything.

**Comment by ilianagenkova** [comment]
@jbathegit  thanks for explaining how this works, I like it!

@ChristopherHill-NOAA and @nicholasesposito , could you provide a suitable descriptions for CATs 8 and 9?

**Comment by ilianagenkova** [comment]
@jbathegit , please set categories 8 and 9 to "Reserved" . 

Looking through the code 8 was used for the now retired SSM/I and 9 was never used (it seems to me). thanks!

**Comment by jbathegit** [comment]
OK, I'll get this in the next update, which will probably be in about a month or so since that's when version 40 of the WMO master tables is due to be released.
