### ISSUE TITLE
should .inc files be included in cmake build lists of files?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#43]
@aerorahul I would welcome input on this one.

In autotools systems I would expect to include the .inc files in the list of code files. In that way dependencies can be tracked. (That is, changes in the inc file could trigger rebuild of files that depend on it.

Is that not the case is cmake?

We have a file src/bufrlib.inc (formerly src/bufrlib.prm), but it is not part of the cmake list of sources for the NCEPLIBS-bufr library.

**Comment by aerorahul** [comment]
I would say yes, because if one changed the `.inc` file, you want that change to trigger recompilation of the source code that includes it.
