### ISSUE TITLE
Test for recent burflib.prm (and proposed) changes?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#44]
OK, up to now we have just renamed a file. But the next step is to create the inc file at build time, instead of having it in the repo. The inc file will then look like as shown below.

Note that the MAXNC and the MXNAF parameters will get substituted values.

Do we have any tests that specifically depend on MAXNC and MXNAF?

```
C-----------------------------------------------------------------------
C	Maximum number of Section 3 FXY descriptors that can be
C	written into a BUFR message by the BUFRLIB software.

	PARAMETER ( MAXNC = @MAXNC@ )
C-----------------------------------------------------------------------
C	Maximum number of entries in the internal string cache.

	PARAMETER ( MXS = 1000 )
C-----------------------------------------------------------------------
C	Maximum number of entries in the internal descriptor list cache.

	PARAMETER ( MXCNEM = 450 )
C-----------------------------------------------------------------------
C	Maximum number of 2-04 associated fields that can be in effect
C	at the same time for any given Table B descriptor.

	PARAMETER ( MXNAF = @MXNAF@ )
C-----------------------------------------------------------------------
C	BUFRLIB "missing" value.  The default value for BMISS is set
C	within subroutine BFRINI, but it can be modified by the user via
C	a subsequent call to subroutine SETBMISS.

	COMMON /BUFRBMISS/ BMISS
	REAL*8  BMISS
C-----------------------------------------------------------------------
```

**Comment by jbathegit** [comment]
I just submitted a [pull request](https://github.com/NOAA-EMC/NCEPLIBS-bufr/pull/45) to address the issue of having parameters defined in multiple locations, but now it sounds like you want to handle this in a different way?

**Comment by jbathegit** [comment]
We could certainly add on to the top of my recent changes, to have the source definitions for MXNAF and MAXNC now defined in bufrlib.h.in and then use those to generate bufrlib.inc on the fly.  But if we generate bufrlib.inc on the fly, then from where should we copy over the content for MXS, MXCNEM and BMISS, which are currently only ever defined in bufrlib.inc?

**Comment by edwardhartnett** [comment]
OK, I had a different idea of where this is going, but first let me re-ask the question. Do we have a test which would fail if we broke any of these constants?

**Comment by jbathegit** [comment]
Yes, test_OUT_2.f already includes a test for the value of BMISS.  But the other 4 values are parameters, which by definition are fixed at compile time and can never change after that.  So we don't currently have any direct tests for those values, and off the top of my head I'm not even sure how we would do that, because those parameters are all used in low-level (i.e. deep down-in-the weeds) routines that aren't directly accessible from within an application program.

Unfortunately this isn't OO code with well-defined classes where we can just easily add a new public test method to each class.  So I'm not sure how we could address this(?)

**Comment by jbathegit** [comment]
FWIW, test_IN_1.f and test_IN_4.f both exercise the Section 3 decoding logic, which means they would both fail rather quickly at a lower level (i.e. inside of reads3.f) if either MAXNC or MXCNEM wasn't set properly.

Similarly, all but one of the test programs calls UFBINT to read or write individual data values, and any of those would fail rather quickly at a lower level (i.e. inside of string.f) if MXS wasn't set properly.

So I think we're OK in that regard, and please understand that I'm happy to add more test programs at a later date to more thoroughly put the library through its proverbial paces, and based on the output of gcovr as described in #32.  But I was just hoping to make more of a dent in the documentation (Doxygen docs) first.
