### ISSUE TITLE
add tests to increase test code coverage

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#445]
add tests to increase test code coverage

This is a catch-all issue for test improvements that are not part of a specific test issue.

**Comment by edwardhartnett** [comment]
We are making great progress in testing.

As of today, we have 84.5% test coverage, up almost 10% from when we started this test campaign. Thanks to @AlexanderRichert-NOAA , @jbathegit , and @jack-woollen for the great effort here.

We still have a ways to go. When I look at the code coverage report, I still see a lot of red...

![image](https://user-images.githubusercontent.com/38856240/234861706-a7788ac8-5cd7-45a0-98cb-e8ec0942d1a1.png)

![image](https://user-images.githubusercontent.com/38856240/234861863-a93c6598-d01c-4787-857f-551fbb34a629.png)

**Comment by edwardhartnett** [comment]
Tremendous progress here:

![image](https://github.com/NOAA-EMC/NCEPLIBS-bufr/assets/38856240/644978bb-30f9-424e-8ae7-0af05763a69f)

**Comment by jbathegit** [comment]
Testing is now at 95.5%, so we should probably consider closing this issue

![Capture6](https://github.com/NOAA-EMC/NCEPLIBS-bufr/assets/62722702/1383f04d-b688-4f2e-9abf-b580e85827a3)

**Comment by edwardhartnett** [comment]
Awesome!

![image](https://github.com/NOAA-EMC/NCEPLIBS-bufr/assets/38856240/11a366cd-3b65-4765-aad8-69a6de482f74)
