### ISSUE TITLE
do we have a memory leak here?

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/NCEPLIBS-bufr#474]
I could be way off base here, but I wanted to throw this out there just in case I may have stumbled on to something important.

In bufr_c2f_interface.F90, we currently have the following private function:
```  
    !> Convert a C string into a Fortran string.
    !> 
    !> @param c_str - Pointer to a null-terminated C string
    !> @param f_str - Fortran string
    !> 
    !> @author Ronald McLaren @date 2020-07-29
    function c_f_string(c_str) result(f_str)
      character(kind=c_char,len=1), intent(in) :: c_str(*)
      character(len=:), allocatable :: f_str
      integer :: nchars
      
      nchars = 1
      do while (c_str(nchars) /= c_null_char)
          nchars = nchars + 1
      end do 
      nchars = nchars - 1
      
      allocate(character(len=nchars) :: f_str)
      f_str = transfer(c_str(1:nchars), f_str)
    end function c_f_string
```
This function is called by a number of other wrapper routines in this file, but note that the return value is an allocated array.  And it doesn't look like this memory ever gets deallocated whenever this function gets called.  Furthermore, it doesn't even look like there's a straightforward way to do this since we're often just passing the return value directly as an argument to another routine from within the calling routine, as in:

`call nemdefs ( file_unit, c_f_string(mnemonic), desc_f, unit_f, iret)`
or
`ires = iupbs01(bufr,c_f_string(mnemonic))`

So how does that allocated memory ever get cleanly deallocated?  Or am I missing something here?

@edwardhartnett @rmclaren @jack-woollen @AlexanderRichert-NOAA please advise - thanks!

**Comment by AlexanderRichert-NOAA** [comment]
I'm still digging, but of what I've seen so far it looks like this is okay. From what I can tell, unlike in C, in Fortran an allocated array is automatically deallocated when a function call is complete. In any case I'm not sure if there's a good way to test this for ourselves.

**Comment by rmclaren** [comment]
https://fortran-lang.org/en/learn/best_practices/allocatable_arrays/ (first sentence)

I ran all this code through valgrind in order to make sure there are no leaks... It's been a while, but I was pretty careful.

**Comment by edwardhartnett** [comment]
Adding a comment to the code explaining this would be very helpful. If it causes confusion once, it will do so again and again.

**Comment by jbathegit** [comment]
Thanks for the prompt replies everyone!  This eases my mind, and I'll add a comment as part of my next commit for #472.
