### ISSUE TITLE
transfer text from external HTML docs to user_guide.md and code files in repo

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#48]
As discussed in meeting on 11/2/20, there is an external HTML documentation site for NCEPLIBS-bufr. It should be referenced in the README. (@jbathegit can you put the link in this issue or in the README?)

This external documentation contains additional text that describes NCEPLIBS-bufr and its functions.

Some of the external docs refers to specific functions and can be moved to those code files. Other parts are general and will be moved to user_guide.md (or perhaps other .md files in the docs directory if needed).

This is related to #15

**Comment by jbathegit** [comment]
The URL for the external HTML documentation is now in the new UserGuide.md, as of PR #76

**Comment by jbathegit** [comment]
This has been completed effective with the v11.5.0 release.
