### ISSUE TITLE
use ibfms in test_ufbcup.F90

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/NCEPLIBS-bufr#486]
Tests such as the following in test_ufbcup.F90 can be handled with the library routine ibfms, rather than hardcoding 10E10_8 constants and EPSILON-style fuzziness thresholds:

```
  if (hdr(1,1) .ne. 100000000000.00000_8) stop 30
  
  ! Get SID, the station ID.
  call ufbint(12, hdr, 1, 1, iret, 'SID')
  if (station .ne. 'CWGN    ') stop 31

  ! Get the MISSING value.
  call ufbint(12, hdr, 1, 1, iret, 'NUL')
  missing = hdr(1, 1)
  if (abs(hdr(1, 1) - 100000000000.00000_8) > EPSILON) stop 32
  
  ! Get and check more values.
  call ufbint(12, hdr, 1, 1, iret, 'XOB')
  if (abs(hdr(1, 1) - 262.43) > EPSILON) stop 40
  call ufbint(12, hdr, 1, 1, iret, 'YOB')
  if (abs(hdr(1, 1) - 49.03) > EPSILON) stop 41
  call ufbint(12, hdr, 1, 1, iret, 'DHR')
  if (abs(hdr(1, 1) - 0.0) > EPSILON) stop 42
```

**Comment by edwardhartnett** [comment]
Since this is a working test, let's leave this until all other testing is complete.

We still have one out of eight lines of code completely untested.

**Comment by jbathegit** [comment]
That's fine - my only intent here was to get it documented as an issue, so that we don't forget to circle back to it at some point.
