### ISSUE TITLE
Next release tag

### ISSUE THREAD

**Issue by emilyhcliu** [NOAA-EMC/NCEPLIBS-bufr#503]
The JCSDA JEDI project needs a new release tag which includes a feature added by @rmclean (PR #451).
When will the next release tag be available from GitHub?

**Comment by jbathegit** [comment]
Hopefully very soon.  Rest assured we haven't forgotten about this.  We're just chasing down a few final commits to be included in this release.

**Comment by jbathegit** [comment]
FYI the new release tag will be 12.0.0.  Ron already asked about this in #462, so we know you're eagerly waiting for it :-)

**Comment by emilyhcliu** [comment]
Jeff,

Got it!!  Thanks for letting us know the status of the release.

Emly

*Emily Huichun Liu*
Physical Scientis
Modeling and Data Assimilation Branch - DA & QC
NOAA/NWS/NCEP Environmental Modeling Center
National Centers for Weather and Climate Prediction (NCWCP)
5830 University Research Court
College Park, MD 20740
Phone: 301-683-3639
Cell: 410-948-6256
