### ISSUE TITLE
Update print statement for binv

### ISSUE THREAD

**Issue by ilianagenkova** [NOAA-EMC/NCEPLIBS-bufr#508]
This is a minor issue, but it would be helpful to see it fixed. With some of the largest dcom tanks, the binv print statement needs to be updated:
ls /lfs/h1/ops/prod/dcom/20230530/b012/xx023
-rw-rw-r-- 1 ops.prod prod     **6.5G** May 31 03:26 /lfs/h1/ops/prod/dcom/20230530/b012/xx023
binv /lfs/h1/ops/prod/dcom/20230530/b012/xx023 
type        messages       subsets         bytes 
NC012023      128487     513174808    ******     3993.98
TOTAL         128487     513174808    **********

Smaller tank sizes are inventoried fine:
-rw-rw-r-- 1 ops.prod prod     **4.6G** May 31 03:29 /lfs/h1/ops/prod/dcom/20230530/b021/xx206

binv /lfs/h1/ops/prod/dcom/20230530/b021/xx206
type        messages       subsets         bytes
NC021206       27116       5832000     **560076499**      215.08
TOTAL          27116       5832000     560076499

thanks

**Comment by jbathegit** [comment]
This was a simple fix that literally took me 10 minutes to figure out, so I'll go ahead and include it in the upcoming release.
