### ISSUE TITLE
update to subroutine STNDRD, including new test case

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/NCEPLIBS-bufr#51]
In my BUFRLIB repository in VLab, I have an update to subroutine STNDRD that I'd been planning to introduce in the next version for the WCOSS and on my website.  Now that I'm working to fully merge everything into the NCEPLIBS-bufr repository on GitHub, I'd like to bring this update over to GitHub and just work from there going forward.

The update to the subroutine fixes an internal calculation when standardizing messages which contain only one subset.  It was discovered after researching a WCOSS operations failure back in March, and it was temporarily patched there, but now I'd like to bring the patch into the GitHub baseline.  I still have the failed WCOSS test case saved off from March, and I'll include it as part of a new test program once I submit a pull request for this issue.

**Comment by jbathegit** [comment]
@edwardhartnett @aerorahul 

I'm about ready to submit a pull request for this.  It will be a new test_OUT_4.f program which includes tests for this source change as well as #52, #53 and #54, plus some additional subprogram tests that I know haven't been covered yet within the existing test suite.  So the main connecting thread in the pull request will be the test_OUT_4.f program which is a good new comprehensive test code.  However, just like the existing test_OUT_3.f program, it involves dynamic allocation so I guess will only be applicable for Intel builds.

Here's where I'm stuck - everything works in my offline testing, but I'm unable to do a full integration test because I don't have write permission to the /home/ftp/emc/static_files/public directory on emcrzdm, and therefore I can't update the bufr.tar file for the curl/wget pull.  Could one of you please allow me to update that file?  My account is jator2 which is part of the emc group, so I believe if you just do a chmod 775 on the directory (group write permission) then I should be good to go.  (Thanks! ;-)

**Comment by aerorahul** [comment]
@jbathegit 
I don't have permissions to write to that space either.
I would email @EricRogers-NOAA with a path to the updated tarball, and ask him to replace it with the one you provide.

**Comment by edwardhartnett** [comment]
Awesome progress! Maybe you can put this up as a draft PR while you get the tar file updated? Also maybe @kgerheiser has write permissions for that file?

**Comment by EricRogers-NOAA** [comment]
The tarball belongs to emc.glopara on RZDM:

/home/ftp/emc/static_files/public
[emc@vm-lnx-emcrzdm02 public]$ ls -l
total 9788
-rw-r--r--. 1 emc.glopara emc 9964544 Jul 22 16:15 bufr.tar
drwxr-xr-x. 2 emc.glopara emc    4096 Oct  2 13:47 CCPA
drwxr-xr-x. 3 emc.glopara emc    4096 Sep 17 18:34 UFS
drwxr-xr-x. 2 emc.glopara emc    4096 Nov  3 20:21 WW3

We need whoever put it there (maybe Kate?) to change permissions so Ed can replace it.

Eric

**Comment by edwardhartnett** [comment]
It's more important that @jbathegit have permissions. ;-)

**Comment by jbathegit** [comment]
jator2@vm-lnx-emcrzdm02.ncep.noaa.gov [/home/ftp/emc/static_files/public (49)] % ls -la
total 9796
drwxr-xr-x. 5 emc.glopara emc    4096 Oct  2 13:45 ./
drwxrwxrwx. 3 emc         emc    4096 Aug  3 14:22 ../
-rw-r--r--. 1 emc.glopara emc 9964544 Jul 22 16:15 bufr.tar
drwxr-xr-x. 2 emc.glopara emc    4096 Oct  2 13:47 CCPA/
drwxr-xr-x. 3 emc.glopara emc    4096 Sep 17 18:34 UFS/
drwxr-xr-x. 2 emc.glopara emc    4096 Nov  3 20:21 WW3/

So interestingly the parent directory is world-writeable, but not the directory itself, which is what I really need in order to swap out a new bufr.tar file.  So I basically need whoever owns the emc.glopara account to do a "chmod 775 public" from within the /home/ftp/emc/static_files directory.

@KateFriedman-NOAA are you the right person to ask?  All I can see in /etc/passwd is the following, which doesn't tell me very much about who really owns this account:

jator2@vm-lnx-emcrzdm02.ncep.noaa.gov [/home/ftp/emc/static_files/public (51)] % grep emc.glopara /etc/passwd
emc.glopara:x:9019:3000:Shared EMC:/home/people/emc/emc.glopara:/bin/bash

**Comment by EricRogers-NOAA** [comment]
I'm emailing Kate, Fanglin, and Russ now about this. 

Eric

**Comment by jbathegit** [comment]
Thanks, and just to clarify, I don't need the "public" subdirectory to be world-writeable, just group-writeable, because my jator2 account is in the emc group.  So a chmod 775 will do the trick as I noted earlier, because the world only needs read permission ;-)

**Comment by jbathegit** [comment]
I'm good with the permissions now, thanks to @EricRogers-NOAA and @yangfanglin   I'll go ahead with final integration testing and then get the pull request submitted.
