### ISSUE TITLE
are there any performance benchmarks for NCEPLIBS-bufr?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#525]
Do we have any programs that measure the performance of the library? 

If so, do we test each version to ensure the performance is not regressing?

**Comment by jbathegit** [comment]
The CI tests we have now confirm the correctness of encoding and decoding for a variety of scenarios, but there are no benchmarks in terms of overall speed or efficiency.

**Comment by edwardhartnett** [comment]
OK, thanks, you may consider adding some...
