### ISSUE TITLE
Add IntelLLVM (OneAPI) support

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [NOAA-EMC/NCEPLIBS-bufr#538]
Adding IntelLLVM (OneAPI) support, including CI workflows, to NCEPLIBS.

**Comment by jbathegit** [comment]
Hey @AlexanderRichert-NOAA, just touching base on this issue which was an offshoot of #536.  Has there been any progress by Intel in resolving the C bindings/data sizes bug in their OneAPI Fortran compiler?

I'm expecting to do a new v12.1.0 release of NCEPLIBS-bufr within the next 30 days, so I'll be happy to include any updates for this in that release if there's any resolution by then.  Or we can just wait for the next subsequent release, which is also fine by me.  No worries either way and just lmk - thanks!

**Comment by AlexanderRichert-NOAA** [comment]
Supposedly the issue will be fixed in OneAPI 2024.2, which should be coming out soon ("mid 2024"). I'll keep an eye out and put in a PR as soon as that new version comes out.
