### ISSUE TITLE
Python wrapper doesn't build for Python 3.12+

### ISSUE THREAD

**Issue by rmclaren** [NOAA-EMC/NCEPLIBS-bufr#561]
Unfortunately the numpy.distutils package has been deprecated (used in the setup.py script). As a result the python bindings will not build on machines running the newest version of python..

**Comment by jbathegit** [comment]
Sorry if I'm missing something or if I'm just being dense, but I can't seem to find the setup.py script that you're referencing.  Is it somewhere in the python subdirectory?

**Comment by rmclaren** [comment]
`NCEPLIBS-bufr/python/setup.py.in` I guess it gets copied to the build directory as setup.py.

**Comment by jbathegit** [comment]
I still don't see that anywhere.  The latest `develop` branch of the library only has the following.  Is it possible you're looking at an older clone of the repository?

![Capture](https://github.com/NOAA-EMC/NCEPLIBS-bufr/assets/62722702/f9ec57b6-06eb-429d-96f9-e7d3bb59d560)

**Comment by rmclaren** [comment]
Looks like someone already converted to use meson instead of distutils... Sorry..
