### ISSUE TITLE
do we still need -DENABLE_TESTS=ON?

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/NCEPLIBS-bufr#57]
@edwardhartnett @aerorahul 

Now that testing is enabled by default, do we still need -DENABLE_TESTS=ON in README.md (in the Installation instructions) and in .github/workflows/main.yml?  It might be cleaner if we just remove these - any thoughts?

**Comment by aerorahul** [comment]
Get rid of the option in README.md.  It does not exist as an option in the build.

**Comment by jbathegit** [comment]
OK will do, but can we also remove it from .github/workflows/main.yml?

This relates to the (now closed) #19.  We did enable testing by default, but we never removed -DENABLE_TESTS=ON from all of the places where this was explicitly (and now redundantly ;-) set.

**Comment by edwardhartnett** [comment]
Yes it can be removed everywhere.
