### ISSUE TITLE
Unused subroutines?

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [NOAA-EMC/NCEPLIBS-bufr#598]
The following functions do not appear to be used in operational executables, WCOSS2 decoders, or in any executable under spack-stack:
- [ ] mrginv
- [ ] setim8b
- [ ] sntbestr
- [ ] ufbsp

@jbathegit are these subroutines needed and used? If so, please feel free to close this issue; this is part of an inventory of NCEPLIBS subroutines and trying to identify any code that can be safely removed.

**Comment by jbathegit** [comment]
sntbestr and ufbsp are only ever called internally by other routines within the library, not by any external application codes.

setim8b was only recently introduced in v12.0.0 of the library, so I think as more codes begin to migrate away from older versions of the library then you'll see more usage of that routine, at least for codes which are compiled using 8-byte integers.

As for mrginv, as far as I know that's only ever used in the bufr_dupmrg and bufr_dupmar codes in the bufr_dump package (see https://github.com/NOAA-EMC/bufr-dump).  But it is still used/needed :-)
