### ISSUE TITLE
retire ufbin3 and nevn routines from library?

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/NCEPLIBS-bufr#601]
@jack-woollen @HuiyaChuang-NOAA @ilianagenkova 

There are two routines in the NCEPLIBS-bufr library which, according to their respective docblocks, are/were only ever used for NCEP prepfits files in the gridtobs program.  My question is whether prepfits files and the gridtobs program are still even used for verification purposes, and, if not, whether we can plan to go ahead and retire the ufbin3 and nevn routines from the library at some point?  Or would we still need to keep them around for use with historical archives?

I'm just putting this question out there to see if there may be an opportunity here to lighten our ongoing code maintenance load a bit :-)  Please let me know, and please also feel free to pass this query along to anyone else who may be able to provide relevant input/guidance - thanks!

**Comment by jack-woollen** [comment]
@jbathegit I agree ufbin3 is similar to ufbevn, with one difference. Ufbin3 returns jret along with iret, which is useful. Maybe make jret an optional output  argument from ufbevn, then all functionality is maintained.

**Comment by jbathegit** [comment]
Thanks for the reply Jack, but my main question is whether prepfits and gridtobs are still even run on WCOSS2 for verification or otherwise used anywhere at NCEP?  That's also why I pinged @HuiyaChuang-NOAA and @ilianagenkova for their input.

Bottom line - at least according to the current docblock, the ufbin3 routine is only for use in prepfits.  So unless that's not true and the docblock isn't fully correct, then if by some chance prepfits is now obsolete, then maybe(?) we can remove ufbin3 and nevn altogether from the library at some point, and unless maybe they need to be retained for use with historical archives(?)

Again, just wanted to float the question out there... :-)

**Comment by jack-woollen** [comment]
Sorry Jeff, no idea what the status of prepfits is!

**Comment by ilianagenkova** [comment]
I did chat with Shelley about this, she recommended we tag @AliciaBentley-NOAA  - Alicia, could you check if the new verification is using **ufbin3** and **nevn**?

I did not find any current calls to ufbin3 and nevn in obsproc, prepobs, bufr-dump, satingest, bufr-tranjb and sfcship (all repos that ObsProc manages). Only a commented out call to ufbin3 in prepobs.

**Comment by AliciaBentley-NOAA** [comment]
@ilianagenkova Thanks! I checked our repositiory, and neither **ufbin3** or **nevn** appear in the EVS v1.0. I'll tag @malloryprow too, since I think she might use some of the old verf_precip code in her global archive code. Hopefully it's not the part that uses **ufbin3** and **nevn**!

**Comment by malloryprow** [comment]
@AliciaBentley-NOAA Not seeing anything in https://github.com/malloryprow/emc-global_archive/blob/main/sorc/ccpa24hr_accum.f that came from verf_precip.

**Comment by jbathegit** [comment]
OK, thanks everyone for checking.  I'll be releasing the next version 12.1.0 of the library in the next few weeks, so once that's out of the way I'll work on retiring these two routines from the library altogether.
