### ISSUE TITLE
Add Python Api

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/NCEPLIBS-bufr#61]
Add Python Api from Jeff Whitaker. 
The python api is used in JEDI IODA projects.

**Comment by edwardhartnett** [comment]
Is building this in CMake optional? That is, what is someone wants to build NCEPLIBS-bufr but they don't want the python API?

Testing is required.

**Comment by edwardhartnett** [comment]
Also, is this code just copied from Jeff's library? Is that wise? Have we mentioned this to Jeff?

If this becomes part of NCEPLIBS-bufr, does Jeff plan to rely on this version and retire his version? Or are we creating another copy of this code that NOAA will have to maintain?

**Comment by aerorahul** [comment]
Jeff transferred this to the JCSDA org because they were using it. It came with a version of the bufr source code.  I brought it here because we are now facing an issue with incompatible bufr source code.

The hope is to have a single repo with the bufr fortran, C and Python API's. 

Jeff is a reviewer on the PR.

**Comment by edwardhartnett** [comment]
@jswhit2 apparently we are ending up with some of your python code and may be merging it into the NCEPLIBS-bufr library. Were you aware of this? Are you planning on maintaining your own copy of this code? Or will NCEPLIBS-bufr be its only home?

Who will maintain this code? @jbathegit are you comfortable taking this on?

**Comment by edwardhartnett** [comment]
@aerorahul please answer the questions about how this will work in the cmake build.

**Comment by edwardhartnett** [comment]
@aerorahul you've taken down the PR, which is fine because it needs work. But you've also closed the issue?

**Comment by aerorahul** [comment]
Opening another one in this place.

**Comment by aerorahul** [comment]
Building with python API is optional i.e. the bufr library can be built as is in Fortran 77.

**Comment by jbathegit** [comment]
For my part, and as I mentioned in #60, I think it will be great to have a Python API available in the NCEPLIBS-bufr bundle, especially if it can be cleanly integrated and if it's the same one that JEDI IODA is currently using.

**However**, I am not proficient in Python, and therefore I am not "comfortable taking this on" if what you're asking me to do is to continue being the sole NCEPLIBS-bufr code manager going forward.  I would need help in managing this new API, including troubleshooting if something goes wrong.  I'm good with the Fortran and C aspects of BUFRLIB, but I can't step up to assume primary responsibility for an API in a different language that I have very little personal experience with.

If someone else can step up to fill that role, then I think this is workable, and again I welcome the overall concept as well as the potential collaboration.

**Comment by edwardhartnett** [comment]
In addition to the code, we would need  on-going assistance with maintenance. So why not just leave it separate?

NCEPLIBS-bufr is the core engine, it does not have to include every language add-on. Similar to netCDF or HDF5 C/Fortran libraries, it provides services for other language layers.

**Comment by aerorahul** [comment]
@jbathegit I am willing to provide 1 year of support for the python API.  Surely, 1 year is enough to find someone to learn 584 lines of python code in `__init__.py` (A lot of it is documentation).

**Comment by edwardhartnett** [comment]
@aerorahul your support is appreciated. We will clear this up the supervisory chain.

Did we come up with a time frame when this is required? That is, when is the public release that needs to include this?

We will need good testing before this is merged, and also we need to work out documentation issues. End users should see the python API docs alongside the Fortran docs.

**Comment by aerorahul** [comment]
> @aerorahul your support is appreciated. We will clear this up the supervisory chain.
> 
> 
> 
> Did we come up with a time frame when this is required? That is, when is the public release that needs to include this?
> 
> 
> 
> We will need good testing before this is merged, and also we need to work out documentation issues. End users should see the python API docs alongside the Fortran docs.
> 
> 
> 
> 

Please define what you mean by good testing. 
Please help how to put python API docs alongside FORTRAN docs.

**Comment by jbathegit** [comment]
@aerorahul  I also appreciate the offer of support.  I'm sure I can eventually learn enough Python to be helpful (or dangerous, depending on how you look at it ;-), but in the bigger picture I have a general concern with how much additional work this is going to be for me personally to field inquiries, answer questions, and provide support for the package as a whole, especially after your proposed 1-year term of support for the Python API expires.

I realize we have a whole team of capable folks in the NCEPLIBS team, but at the end of the day my name is still listed as the code manager for NCEPLIBS-bufr, which means every time something new gets added to the package, the more people are going to ask of and expect from me in terms of ongoing time and resources.  As long as there are NCEPLIBS team members or others who can and will back me up beyond that first year, then I'm OK with this, and again I do like this overall concept which expands the usefulness of the library to a whole new category of users.

With that said, and if we do go ahead with this, will Jeff W. now be viewing NCEPLIBS-bufr as the official repository for this API and redirecting all future support inquiries to us?  If not, then whenever he makes updates will he provide them to us so we can stay in sync going forward?  Just want to make sure we're all (including Jeff W.) on the same page here and have the same shared understanding of how this is going to work.

**Comment by jswhit** [comment]
as the developer of the python interface, I'm happy to help.  As @jbathegit  mentioned, if we do this the NCEPLIBS-bufr should become the official repo.

**Comment by aerorahul** [comment]
closed via #66
