### ISSUE TITLE
reading from BUFR message header

### ISSUE THREAD

**Issue by ilianagenkova** [NOAA-EMC/NCEPLIBS-bufr#616]
How does one read the time stamp in a BUFR message?
I only know how to read it from subsets.

**Comment by ilianagenkova** [comment]
@SteveStegall-NOAA , hopefully we can use this for the receipt time in the satingest tanks.

**Comment by jbathegit** [comment]
The easiest way to read in the year, month, day, hour, minute, etc. (or any other Section 1 value, for that matter :-) is via the function [iupvs01](https://noaa-emc.github.io/NCEPLIBS-bufr/s013vals_8F90.html#a3b1a6e580f306826c680ff0a71d883f8).

**Comment by jbathegit** [comment]
I just saw your second comment to Steve.  The time values I mentioned in my previous reply are valid for the actual data in the message, not the NCEP tank receipt time which is a completely different animal.  If you want the tank receipt time then you need to use subroutine [rtrcpt](https://noaa-emc.github.io/NCEPLIBS-bufr/tankrcpt_8F90.html#a5d6fa241d34622347252bf41b73d8610).

**Comment by ilianagenkova** [comment]
Thanks, Jeff!
