### ISSUE TITLE
Need Python API to the BUFR library for JEDI IODA projects.

### ISSUE THREAD

**Issue by aerorahul** [NOAA-EMC/NCEPLIBS-bufr#62]
The JEDI IODA projects use python API's to the bufr library for converting BUFR data into IODA data format.
One such API is the py-ncepbufr developed by Jeff.Whitaker and is currently housed in the JCSDA github repository [here](https://github.com/JCSDA-internal/py-ncepbufr)

This is a requirement for the JEDI IODA project.

Until then, we will continue to use the one under JCSDA organization.

**Comment by edwardhartnett** [comment]
It's not clear that there is great benefit in this code moving to NCEPLIBS-bufr. For example, Jeff's netcdf-4 python package co-exists quite happily with netcdf-c, and is completely separate in every way.

This is currently hosted by JOINT CENTER FOR SATELLITE DATA ASSIMILATION (JCSDA), and presumably supported under that project. Is there a reason that cannot continue?

Do we know of some need within the next (i.e. v3) release of the UFS that a python API is needed? Or is this primarily to benefit additional (but non-operational) processing? In that case, it does not need to be in NCEPLIBS-bufr.

**Comment by aerorahul** [comment]
It is being used in the JEDI ocean data assimilation system for preprocessing the marine observations.
This system is targeted for operational implementation.

**Comment by edwardhartnett** [comment]
@aerorahul when is this targeted for operational implementation? Do we know?

Has responsibility for this API been discussed before? Clearly not with @jbathegit or myself - anyone else? @jswhit2 I would welcome your views on where this code should be kept.

NCEPLIBS-bufr is already a busy project under active development, with only one person assigned. Adding a whole new language API to the project is non-trivial.

**Comment by aerorahul** [comment]
The Reanalysis project is supposed to do trials starting January 2021 and scout runs in March.
The NG GODAS project is on a similar time line.
The Reanalysis is not an operational implementation.
The NG GODAS is to replace the operational GODAS.

**Comment by aerorahul** [comment]
closed via #66
