### ISSUE TITLE
should YAML files be .yml or .yaml?

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/NCEPLIBS-bufr#624]
@edwardhartnett @AlexanderRichert-NOAA @Hang-Lei-NOAA

I've noticed that all of the YAML filenames in all of the NCEPLIBS `.github/workflows` subdirectories seem to use .yml as a suffix rather than .yaml.  Is there any particular reason for this?

I'm asking b/c the latter seems to be more the preferred industry standard, at least according to https://yaml.org/faq.html and https://stackoverflow.com/questions/22268952/what-is-the-difference-between-yaml-and-yml-extension.  In fact, the latter is already used within the `spack/spack.yaml` file within the NCEPLIBS-bufr repository, so there's also some inconsistency in that regard if we continue to use .yml for the files within `.github/workflows`.

Again, not a big deal, but just curious if there's any particular reason for this, and if not then would it be worthwhile to try and move towards what seems to be the preferred industry standard here?

**Comment by Hang-Lei-NOAA** [comment]
Hi Jeff

The only difference between .yaml and .yml is the file extension. Both are
used for YAML files, and they function the same way.

Your point is good. A consistent choice is better.

Thanks
Hang

**Comment by jbathegit** [comment]
@Hang-Lei-NOAA @edwardhartnett @AlexanderRichert-NOAA 

So we seem to agree that it would be good to be consistent across all of the NCEPLIBS, but do we have an agreement about which extension to gravitate towards?  It seems to me that the .yaml extension may be the preferred industry standard, but I could be wrong about that(?)

**Comment by edwardhartnett** [comment]
Only one way to settle this: https://www.youtube.com/watch?v=Chv9TPtaX-E

**Comment by jbathegit** [comment]
> Only one way to settle this: https://www.youtube.com/watch?v=Chv9TPtaX-E

OK that seems a bit harsh  :-))

Does anyone have a problem if I try making this change to use `.yaml` throughout NCEPLIBS-bufr?  Then, assuming it works w/o any problems, others can likewise switch over the other NCEPLIBS at some later date so they're all consistent?
