### ISSUE TITLE
Some tests for intel only?

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/NCEPLIBS-bufr#63]
From another issue or PR (can't remember which) it turned out that some tests are run for intel compiler only?

What's that about?

That will make it hard to run good testing. Also, it's not clear why the compiler should make that much of a difference in a test. Perhaps the test can be re-worked to also work on gnu.

To answer a question from @jbathegit I don't know of any way of measuring code coverage for intel compilers, nor do I have one on my development system. So that's uncharted territory.

Also our CI system runs on GNU. So we are not running those intel tests and they are doing us little good.

**Comment by jbathegit** [comment]
Yes, I brought this up in #17.  Basically, we currently have the following in test/CMakeLists.txt:

# OUT_3 and OUT_4 tests only run with DA library and Intel
if(CMAKE_C_COMPILER_ID MATCHES "^(Intel)$")
foreach(test_src IN ITEMS ${test_OUT_3_srcs} ${test_OUT_4_srcs})
  string(REPLACE ".f" "" testPref ${test_src})
  foreach(kind ${test_kinds})
    if(${kind} MATCHES "^([4|8|d]_DA)$")
      set(test     ${testPref}_${kind})
      set(test_exe ${test}.x)
      add_executable(${test_exe} ${test_src})
      set_target_properties(${test_exe} PROPERTIES COMPILE_FLAGS
                                                   "${fortran_${kind}_flags}")
      add_dependencies(${test_exe} bufr_${kind})
      target_link_libraries(${test_exe} PRIVATE bufr::bufr_${kind})
      bufr_add_test(${test} ${test_exe})
    endif()
  endforeach()
endforeach()
endif()

which means that test_OUT_3.f and test_OUT_4.f are never run under Gnu.

**Comment by jbathegit** [comment]
Fixed during PR #65.  All DA tests now work on Gnu as well as Intel.
