### ISSUE TITLE
where does the content of LICENSE.md ever get displayed?

### ISSUE THREAD

**Issue by jbathegit** [NOAA-EMC/NCEPLIBS-bufr#75]
I'm trying to figure out what this file is used for, since I don't see it being referenced anywhere in any other .md files, and I don't see it displayed anywhere on the GitHub web site.  The content seems important, but again I don't see where it's actually used or displayed anywhere.

Thoughts?

**Comment by edwardhartnett** [comment]
It should be removed.

Where did it come from?

**Comment by aerorahul** [comment]
The Licence is not shown until clicked.
But, on the NCEPLIBS-bufr github page, on the right hand column, one can see it listed in the About column.

We should not remove this file.
It is the LICENSE of the project, and is currently under LGPL 3.0

**Comment by edwardhartnett** [comment]
Who decided to release the code under LGPL 3.0? Is that a NOAA legal department decision? Or a programmer decision?

**Comment by aerorahul** [comment]
NOAA Legal.  Ask @arunchawla-NOAA

**Comment by edwardhartnett** [comment]
OK, then we should leave it and probably put it in every repo so they're all the same.

**Comment by aerorahul** [comment]
All NCEPLIBS repos already have LGPL 3.0 licenses.

**Comment by edwardhartnett** [comment]
OK, so probably this issue should be closed.

**Comment by aerorahul** [comment]
@edwardhartnett Actually, it may be still worth it to go through all and make sure the language and version of the License is consistent and same across all repos.
