### ISSUE TITLE
Possible Standards Violation in moda_mstabs.F

### ISSUE THREAD

**Issue by mathomp4** [NOAA-EMC/NCEPLIBS-bufr#81]
All,

Recently I tried to compile the NCEP_bufr library in GEOS which led to an [issue with compiling with GCC 10](https://github.com/GEOS-ESM/NCEP_Shared/issues/16) with `moda_mstabs.F`:
```
[  0%] Building Fortran object src/Shared/@NCEP_Shared/NCEP_bufr_r4i4/CMakeFiles/NCEP_bufr_r4i4.dir/moda_mstabs.F.o
/discover/swdev/mathomp4/Models/GEOSgcm-with-bufr-GCC10/GEOSgcm/src/Shared/@NCEP_Shared/NCEP_bufr/moda_mstabs.F:39:44:

   39 |    CHARACTER*4, BIND(C) :: CBBW(MXMTBB)
      |                                            1
Error: BIND(C) Variable ‘cbbw’ at (1) must have length one
/discover/swdev/mathomp4/Models/GEOSgcm-with-bufr-GCC10/GEOSgcm/src/Shared/@NCEP_Shared/NCEP_bufr/moda_mstabs.F:42:48:

   42 |    CHARACTER*120, BIND(C) :: CBELEM(MXMTBB)
      |                                                1
Error: BIND(C) Variable ‘cbelem’ at (1) must have length one
/discover/swdev/mathomp4/Models/GEOSgcm-with-bufr-GCC10/GEOSgcm/src/Shared/@NCEP_Shared/NCEP_bufr/moda_mstabs.F:41:46:

   41 |    CHARACTER*8, BIND(C) :: CBMNEM(MXMTBB)
      |                                              1
Error: BIND(C) Variable ‘cbmnem’ at (1) must have length one
/discover/swdev/mathomp4/Models/GEOSgcm-with-bufr-GCC10/GEOSgcm/src/Shared/@NCEP_Shared/NCEP_bufr/moda_mstabs.F:37:45:

   37 |    CHARACTER*4, BIND(C) :: CBSCL(MXMTBB)
      |                                             1
Error: BIND(C) Variable ‘cbscl’ at (1) must have length one
/discover/swdev/mathomp4/Models/GEOSgcm-with-bufr-GCC10/GEOSgcm/src/Shared/@NCEP_Shared/NCEP_bufr/moda_mstabs.F:38:47:

   38 |    CHARACTER*12, BIND(C) :: CBSREF(MXMTBB)
      |                                               1
Error: BIND(C) Variable ‘cbsref’ at (1) must have length one
/discover/swdev/mathomp4/Models/GEOSgcm-with-bufr-GCC10/GEOSgcm/src/Shared/@NCEP_Shared/NCEP_bufr/moda_mstabs.F:40:47:

   40 |    CHARACTER*14, BIND(C) :: CBUNIT(MXMTBB)
      |                                               1
Error: BIND(C) Variable ‘cbunit’ at (1) must have length one
/discover/swdev/mathomp4/Models/GEOSgcm-with-bufr-GCC10/GEOSgcm/src/Shared/@NCEP_Shared/NCEP_bufr/moda_mstabs.F:45:46:

   45 |    CHARACTER*8, BIND(C) :: CDMNEM(MXMTBD)
      |                                              1
Error: BIND(C) Variable ‘cdmnem’ at (1) must have length one
/discover/swdev/mathomp4/Models/GEOSgcm-with-bufr-GCC10/GEOSgcm/src/Shared/@NCEP_Shared/NCEP_bufr/moda_mstabs.F:44:47:

   44 |    CHARACTER*120, BIND(C) :: CDSEQ(MXMTBD)
      |                                               1
Error: BIND(C) Variable ‘cdseq’ at (1) must have length one
src/Shared/@NCEP_Shared/NCEP_bufr_r4i4/CMakeFiles/NCEP_bufr_r4i4.dir/build.make:1903: recipe for target 'src/Shared/@NCEP_Shared/NCEP_bufr_r4i4/CMakeFiles/NCEP_bufr_r4i4.dir/moda_mstabs.F.o' failed
make[3]: *** [src/Shared/@NCEP_Shared/NCEP_bufr_r4i4/CMakeFiles/NCEP_bufr_r4i4.dir/moda_mstabs.F.o] Error 1
CMakeFiles/Makefile2:10370: recipe for target 'src/Shared/@NCEP_Shared/NCEP_bufr_r4i4/CMakeFiles/NCEP_bufr_r4i4.dir/all' failed
make[2]: *** [src/Shared/@NCEP_Shared/NCEP_bufr_r4i4/CMakeFiles/NCEP_bufr_r4i4.dir/all] Error 2
CMakeFiles/Makefile2:10377: recipe for target 'src/Shared/@NCEP_Shared/NCEP_bufr_r4i4/CMakeFiles/NCEP_bufr_r4i4.dir/rule' failed
make[1]: *** [src/Shared/@NCEP_Shared/NCEP_bufr_r4i4/CMakeFiles/NCEP_bufr_r4i4.dir/rule] Error 2
Makefile:2554: recipe for target 'NCEP_bufr_r4i4' failed
make: *** [NCEP_bufr_r4i4] Error 2
```

Note: our version of this file is exactly the same as the one here. 

Now, we are not compiling with `DYNAMIC_ALLOCATION` (for good or ill). Intel seems to not care (at least how we call Intel), but a workaround for now with GNU will be turn that on, but I can't by fiat do that for all compilers since I have no idea how to test the effects (we know GNU can't run our ADAS at the moment).

I'm going to ping @tclune who has the Fortran knowledge to know why this is an issue.

**Comment by tclune** [comment]
Section 18.1.3 Interoperability of intrinsic types in the F2018 standard:

"If the type is character, the length type parameter is interoperable if and only if its value is one."

**Comment by jbathegit** [comment]
What we're trying to do here is to declare Fortran arrays that can be directly accessed within C via the corresponding extern declarations within the header file mstabs.h  As you can see, these are arrays of character strings of fixed lengths of anywhere from 4 to 120 characters, and since this is a static build then the dimensions of all of these arrays are already known and fixed at compile time.

Does the standard that @tclune is referencing mean that we can only have n=1 in the following:
`extern char   MSTABS_BASE(cbsref)[][n]`
and which in turn basically means we should omit the 2nd dimension altogether in these declarations?

For the record, the existing code compiles and runs under all of the compilers we've ever worked with.  That said, I'm certainly open to making any change(s) that will work with Gnu v10, as long as they're backwards-compatible and will still continue to work with all of our other existing compilers.  But as you can see I'm at a bit of a loss here, and I also don't have access to a Gnu v10 compiler of my own to test with, so I'm really hoping somebody else can chime in with a suggestion for a solution.

Please advise - thanks!

**Comment by tclune** [comment]
Yes - the intent of the code is clear, and this aspect of C interoperability has surprised me each time I run into it.

There is no issue per se with the declaration on the C side that you showed.   The construct can definitely be multidimensional.   It is just that you cannot equate a multi-character string in Fortran with an array of single characters.      I'm not aware of the technical reason why this association is disallowed, but if I had to guess, it might have to do with padding that compilers are allowed to insert.  E.g.  `character(10)` might bad out to 16 bytes on some systems.

Basically to be interoperable with C you need a Fortran array of (single) chars.  So this line:
```f90
CHARACTER*12, BIND(C) :: CBSREF(MXMTBB)
```
could be expressed as 
```f90
CHARACTER, BIND(C) :: CBSREF(12, MXMTBB)
```
But I suspect you have Fortran code that uses these variables which will then need some tedious alterations.    

For the record, the existing code compiles and runs with only one of the compilers on my system:  Intel.   (Granted I did not try older GNU compilers).   It fails with GFortran 10.2:
```
bindc.F90:5:39:

    5 |    character(len=2), bind(c) :: foo(10)
      |                                       1
Error: BIND(C) Variable 'foo' at (1) must have length one
```
and with NAG 7.0 (7037)
```
Error: bindc.F90, line 7: BIND(C) variable FOO has CHARACTER(LEN=2)
```

Don't shoot the messenger.  :-)

**Comment by jbathegit** [comment]
OK, thanks for the suggestion @tclune, and I'll take a closer look at making those modifications to `moda_mstabs.F` and how impactful they would be on all of the corresponding Fortran source code.  It may not be too terribly tedious, though it will obviously require some extensive testing.

Furthermore, I'm not sure off the top of my head, but I think the ordering of multiple array indices is different between Fortran and C, so not sure if the C reference `char cbsref[II][JJ]` would be equivalent to `CHARACTER, BIND(C) :: CBSREF(JJ, II)` or `CHARACTER, BIND(C) :: CBSREF(II,JJ)` in Fortran.  I guess trial-and-error and testing will bear that out  ;-)

Either way, I'm going to be out of the office all next week, so I likely won't really dig into this until the following week.

**Comment by tclune** [comment]
Your first suggestion should be right.   `CBSREF(JJ,II)` has the neighboring elements in the first dimension (`JJ`) .  And `cbsref[II][JJ]` has the neighboring elements in the "second" dimension (`[JJ]`).
