### ISSUE TITLE
CTests Failing After Recent merges to NCEPLibs-BUFR

### ISSUE THREAD

**Issue by rmclaren** [NOAA-EMC/NCEPLIBS-bufr#99]
Greg Thompson just noticed that a bunch of CTests are failing after the most recent updates to the develop branch... I updated my repo and got the same result he did. I'm using gcc version 9.3. 

Test project /home/rmclaren/Work/NCEPLIBS-bufr/build
      Start  1: test_IN_1_4_DA
 1/20 Test  #1: test_IN_1_4_DA ...................***Failed    0.00 sec
      Start  2: test_IN_1_4
 2/20 Test  #2: test_IN_1_4 ......................***Failed    0.00 sec
      Start  3: test_IN_2_4_DA
 3/20 Test  #3: test_IN_2_4_DA ...................   Passed    0.03 sec
      Start  4: test_IN_2_4
 4/20 Test  #4: test_IN_2_4 ......................   Passed    0.03 sec
      Start  5: test_IN_3_4_DA
 5/20 Test  #5: test_IN_3_4_DA ...................   Passed    0.05 sec
      Start  6: test_IN_3_4
 6/20 Test  #6: test_IN_3_4 ......................   Passed    0.06 sec
      Start  7: test_IN_4_4_DA
 7/20 Test  #7: test_IN_4_4_DA ...................***Failed    0.00 sec
      Start  8: test_IN_4_4
 8/20 Test  #8: test_IN_4_4 ......................***Failed    0.00 sec
      Start  9: test_IN_5_4_DA
 9/20 Test  #9: test_IN_5_4_DA ...................***Failed    0.05 sec
      Start 10: test_IN_5_4
10/20 Test #10: test_IN_5_4 ......................***Failed    0.06 sec
      Start 11: test_OUT_1_4_DA
11/20 Test #11: test_OUT_1_4_DA ..................   Passed    0.02 sec
      Start 12: test_OUT_1_4
12/20 Test #12: test_OUT_1_4 .....................   Passed    0.02 sec
      Start 13: test_OUT_5_4_DA
13/20 Test #13: test_OUT_5_4_DA ..................   Passed    0.07 sec
      Start 14: test_OUT_5_4
14/20 Test #14: test_OUT_5_4 .....................   Passed    0.07 sec
      Start 15: test_OUT_2_4_DA
15/20 Test #15: test_OUT_2_4_DA ..................   Passed    0.08 sec
      Start 16: test_OUT_2_4
16/20 Test #16: test_OUT_2_4 .....................   Passed    0.09 sec
      Start 17: test_OUT_3_4_DA
17/20 Test #17: test_OUT_3_4_DA ..................   Passed    0.03 sec
      Start 18: test_OUT_4_4_DA
18/20 Test #18: test_OUT_4_4_DA ..................***Failed    0.02 sec
      Start 19: test_gettab
19/20 Test #19: test_gettab ......................   Passed    0.04 sec
      Start 20: test_split_by_subset
20/20 Test #20: test_split_by_subset .............   Passed    2.02 sec

65% tests passed, 7 tests failed out of 20

**Comment by jbathegit** [comment]
Please try it again.  We had recently made updates to the `bufr.tar` archive on emcrzdm (which contains a bunch of fix files for the test process), but until a few minutes ago we had not pushed up the corresponding updates to the above 4 test codes which you noted as having failed.

So I think if you do a `git pull` to update your clone and then try it again, it should work now.  Please let me know - thanks!

**Comment by rmclaren** [comment]
Seems to work now.
